#define IDS_HeaderBadgeTooltipFormat 101
#define IDS_HeaderBadgeConsoleErrorCount 102
#define IDS_HeaderBadgeProfilerActive 103
#define IDS_HeaderBadgeEmulationActive 104
#define IDS_HeaderBadgeConsoleSingleError 105
#define IDS_HeaderBadgeDebuggerPaused 117
#define IDS_HeaderOverflownToolsButtonTooltip 118
#define IDS_HeaderCloseButtonTooltip 119
#define IDS_HeaderMaximizeButtonTooltip 120
#define IDS_HeaderRestoreButtonTooltip 121
#define IDS_HeaderMinimizeButtonTooltip 122
#define IDS_HeaderFeedbackButtonTooltip 123
#define IDS_HeaderDockButtonTooltip 124
#define IDS_HeaderUndockButtonTooltip 125
#define IDS_HeaderBringIEToForegroundButtonTooltip 126
#define IDS_HeaderHelpButtonTooltip 127
#define IDS_HeaderShowConsoleButtonTooltip 128
#define IDS_HeaderHideConsoleButtonTooltip 129
#define IDS_HeaderEmulationDisabledButtonTooltip 130
#define IDS_HeaderEmulationEnabledButtonTooltip 131
#define IDS_HeaderWindowTitle 132
#define IDS_DebuggerDebuggerTooltip 201
#define IDS_DebuggerBreakpointsWindowTitle 202
#define IDS_DebuggerCallstackWindowTitle 203
#define IDS_DebuggerWatchesWindowTitle 204
#define IDS_DebuggerBreakButtonTooltip 206
#define IDS_DebuggerBreakWorkerButtonTooltip 207
#define IDS_DebuggerStepOverButtonTooltip 208
#define IDS_DebuggerStepOutButtonTooltip 209
#define IDS_DebuggerStepIntoButtonTooltip 210
#define IDS_DebuggerBreakOnExceptionButtonAll 211
#define IDS_DebuggerBreakOnExceptionButtonNone 212
#define IDS_DebuggerBreakOnExceptionButtonUnhandled 213
#define IDS_DebuggerBreakOnExceptionButtonTooltip 214
#define IDS_DebuggerPrettyPrintButtonTooltip 217
#define IDS_DebuggerRefreshAllButtonTooltip 218
#define IDS_DebuggerWatchWindowNameColumn 219
#define IDS_DebuggerWatchWindowValueColumn 220
#define IDS_DebuggerWatchWindowIconColumn 221
#define IDS_DebuggerRefreshAllWatchesButton 224
#define IDS_DebuggerRefreshWatchTooltip 225
#define IDS_DebuggerDeleteWatchTooltip 226
#define IDS_DebuggerCloseTabTooltip 227
#define IDS_DebuggerFilePickerTooltip 228
#define IDS_DebuggerBreakpointsDeleteAllButton 229
#define IDS_DebuggerBreakpointsContextMenuGoTo 233
#define IDS_DebuggerBreakpointsContextMenuEnable 234
#define IDS_DebuggerBreakpointsContextMenuDisable 235
#define IDS_DebuggerBreakpointsContextMenuDelete 236
#define IDS_DebuggerTabContextMenuCloseTab 239
#define IDS_DebuggerTabContextMenuCloseAllTabs 240
#define IDS_DebuggerTabContextMenuCloseOtherTabs 241
#define IDS_DebuggerEditorContextMenuDisableBreakpoint 242
#define IDS_DebuggerEditorContextMenuEnableBreakpoint 243
#define IDS_DebuggerEditorContextMenuInsertBreakpoint 244
#define IDS_DebuggerEditorContextMenuRemoveBreakpoint 245
#define IDS_DebuggerEditorContextMenuSetNextStatement 246
#define IDS_DebuggerEditorContextMenuRunToCursor 247
#define IDS_DebuggerStackFramesColumn 248
#define IDS_DebuggerStackFramesColumnTooltip 249
#define IDS_DebuggerLocationColumn 250
#define IDS_DebuggerLocationColumnTooltip 251
#define IDS_DebuggerActiveFrameLabel 256
#define IDS_DebuggerBreakpointLabel 257
#define IDS_DebuggerSearchBoxTooltip 258
#define IDS_DebuggerSearchBoxPlaceholder 259
#define IDS_DebuggerSetNextStatementFailed 260
#define IDS_DebuggerCallstackContextMenuGoToSource 261
#define IDS_DebuggerCallStackContextMenuCopyFrame 262
#define IDS_DebuggerCallStackContextMenuCopyStack 263
#define IDS_DebuggerStackFramesLineColumn 264
#define IDS_DebuggerStackFramesLineColumnTooltip 265
#define IDS_DebuggerDebuggerMainFrame 266
#define IDS_DebuggerCallStackLineColumn 267
#define IDS_DebuggerEditorContextMenuDisableAllBreakpoints 268
#define IDS_DebuggerEditorContextMenuEnableAllBreakpoints 269
#define IDS_DebuggerEditorContextMenuRemoveAllBreakpoints 270
#define IDS_DebuggerFilePickerDynamicNode 271
#define IDS_DebuggerDebuggerTitle 272
#define IDS_DebuggerLocalsWatchExpando 273
#define IDS_DebuggerBreakpointsContextMenuCopy 275
#define IDS_DebuggerBreakpointsConextMenuDeleteAll 276
#define IDS_DebuggerBreakpointsContextMenuEnableAll 277
#define IDS_DebuggerBreakpointsContextMenuDisableAll 278
#define IDS_DebuggerBreakpointsContextMenuAddCondition 279
#define IDS_DebuggerConditionalBreakpointTitle 281
#define IDS_DebuggerConditionalBreakpointLabel 282
#define IDS_DebuggerConditionalBreakpointInstructions 283
#define IDS_DebuggerTracepointMessageTitle 284
#define IDS_DebuggerTracepointLabel 285
#define IDS_DebuggerTracepointInstructions 286
#define IDS_DebuggerAddMessageOkButtonlabel 287
#define IDS_DebuggerAddMessageCancelButtonlabel 288
#define IDS_DebuggerAddMessageMoreInfoButtonlabel 289
#define IDS_DebuggerEditButtonTooltip 290
#define IDS_DebuggerDeleteButtonTooltip 291
#define IDS_DebuggerOkButtonLabel 293
#define IDS_DebuggerCancelButtonLabel 294
#define IDS_DebuggerEditorContextMenuInsertTracepoint 296
#define IDS_DebuggerAddToWatchesWindowLink 297
#define IDS_DebuggerBreakpointsContextMenuAddTraceMessage 298
#define IDS_DebuggerActionsColumnTooltip 299
#define IDS_DebuggerActionsColumn 300
#define IDS_DebuggerLocalsWindowTitle 303
#define IDS_Debuggervs_base_strings_format_date 350
#define IDS_Debuggervs_base_strings_format_time 351
#define IDS_Debuggervs_base_strings_ago_days 352
#define IDS_Debuggervs_base_strings_ago_moreThanADay 353
#define IDS_Debuggervs_base_strings_ago_hours 354
#define IDS_Debuggervs_base_strings_ago_oneHour 355
#define IDS_Debuggervs_base_strings_ago_minutes 356
#define IDS_Debuggervs_base_strings_ago_minute 357
#define IDS_Debuggervs_base_strings_ago_seconds 358
#define IDS_Debuggervs_base_strings_diff_seconds 359
#define IDS_Debuggervs_base_strings_diff_minutes 360
#define IDS_Debuggervs_base_strings_diff_hours 361
#define IDS_Debuggervs_base_strings_diff_days 362
#define IDS_Debuggervs_base_errors_message 363
#define IDS_Debuggervs_base_errors_stackTrace_format 370
#define IDS_Debuggervs_base_errors_error_defaultMessage1 371
#define IDS_Debuggervs_base_errors_error_defaultMessage2 372
#define IDS_Debuggervs_base_errors_error_defaultMessage3 373
#define IDS_Debuggervs_base_performance_timer_startAfterStopError 374
#define IDS_Debuggervs_editor_core_view_view_editorViewAccessibleLabel 376
#define IDS_Debuggervs_editor_core_model_model_mode_tokenizationSupportFailed 378
#define IDS_Debuggervs_languages_typescript_service_languageServiceAdapter_typeInfo 379
#define IDS_Debuggervs_languages_typescript_participants_monacoStyleParticipant_mixedIndentation_message 380
#define IDS_Debuggervs_languages_typescript_participants_monacoStyleParticipant_assignment_message_before 381
#define IDS_Debuggervs_languages_typescript_participants_monacoStyleParticipant_assignment_message_after 382
#define IDS_Debuggervs_languages_typescript_participants_nlsParticipant_needsLocaliztion_message 383
#define IDS_Debuggervs_languages_typescript_participants_symbolUsageParticipant_import_unused 384
#define IDS_DebuggerProfilingRunningMessage 385
#define IDS_DebuggerWatchesShowAllItems 387
#define IDS_DebuggerWatchesRefreshAllTooltip 389
#define IDS_DebuggerWatchesDeleteAllTooltip 390
#define IDS_DebuggerWatchesAddWatchTooltip 391
#define IDS_DebuggerEditorContextMenuAddToWatch 392
#define IDS_DebuggerWatchesContextMenuCopy 393
#define IDS_DebuggerWatchesContextMenuEditValue 394
#define IDS_DebuggerWatchesContextMenuDelete 395
#define IDS_DebuggerWatchesContextMenuDeleteAll 396
#define IDS_DebuggerWatchesContextMenuRefresh 397
#define IDS_DebuggerWatchesContextMenuRefreshAll 398
#define IDS_DebuggerOpenFileFailed 399
#define IDS_DebuggerOpenFileFailedDetail 400
#define IDS_DebuggerOpenFileProgress 401
#define IDS_DebuggerNotAllowedBroken 402
#define IDS_DebuggerNotAllowedRunning 403
#define IDS_DebuggerWaitingForScriptBroken 404
#define IDS_DebuggerWaitingForScriptRunning 405
#define IDS_DebuggerChooserTargetTitle 409
#define IDS_DebuggerChooserRefreshButtonTooltip 410
#define IDS_DebuggerWordWrapOnButtonTooltip 411
#define IDS_DebuggerWordWrapOffButtonTooltip 412
#define IDS_DebuggerShowNextStatement 422
#define IDS_DebuggerContextMenuCopyURL 423
#define IDS_DebuggerContextMenuOpenInBrowser 424
#define IDS_DebuggerContextMenuCopySourceLocation 425
#define IDS_DebuggerNotAvailableMessage 426
#define IDS_DebuggerTypeToFilterWatermark 427
#define IDS_DebuggerNotLoadedMessage 428
#define IDS_DebuggerDebuggerFailedToConnect 429
#define IDS_DebuggerDebuggerFailedToConnectAnotherAttached 430
#define IDS_DebuggerCallstackWindowLibraryFramesHiddenTooltip 433
#define IDS_DebuggerCallstackWindowLibraryFramesVisibleTooltip 434
#define IDS_DebuggerCallstackLibraryCode 435
#define IDS_DebuggerJMCLoadError 438
#define IDS_DebuggerJMCSaveError 439
#define IDS_DebuggerJMCJsonParseError 440
#define IDS_DebuggerSourceMapButtonOffTooltip 444
#define IDS_DebuggerSourceMapOutdatedWarning 445
#define IDS_DebuggerSourceMapNoAuthoredFile 446
#define IDS_DebuggerSourceMapNoMapFile 447
#define IDS_DebuggerSourceMapInvalidJSON 448
#define IDS_DebuggerSourceMapInvalidVersion 449
#define IDS_DebuggerTracepoint 450
#define IDS_DebuggerUnboundBreakpoint 451
#define IDS_DebuggerJustMyCodeDebugMyCodeTooltip 452
#define IDS_DebuggerBreakpointsDisableAllToggleButtonTooltip 453
#define IDS_DebuggerBreakpointsEnableAllToggleButtonTooltip 454
#define IDS_DebuggerEventBreakpoint 465
#define IDS_DebuggerConditionalEventBreakpoint 466
#define IDS_DebuggerEventTracepoint 467
#define IDS_DebuggerEventBreakpointSingleGroup 468
#define IDS_DebuggerEventBreakpointMultiGroup 469
#define IDS_DebuggerBreakpointsAddEventBreakpointButtonTooltip 470
#define IDS_DebuggerBreakpointsAddEventTracepointButtonTooltip 471
#define IDS_DebuggerAddEventBreakpointDialogTitle 472
#define IDS_DebuggerAddEventTracepointDialogTitle 473
#define IDS_DebuggerEventBreakpointsDialogAddButton 474
#define IDS_DebuggerAddEventBreakpointDialogEventLabel 475
#define IDS_DebuggerEventBreakpointInstructions 476
#define IDS_DebuggerEventTracepointInstructions 477
#define IDS_DebuggerEventBreakpointsHelpButtonTooltip 478
#define IDS_DebuggerEventTracepointsHelpButtonTooltip 479
#define IDS_DebuggerFilePickerMyCodeTooltip 481
#define IDS_DebuggerTabContextMenuMarkAsLibraryCode 482
#define IDS_DebuggerWatchesContextMenuAddWatch 483
#define IDS_DebuggerPausedInDebuggerAlert 484
#define IDS_DebuggerTabContextMenuAddSourceMap 485
#define IDS_DebuggerEventBreakpointUnboundDocMode 486
#define IDS_DebuggerCallstackWindowAsyncFramesHiddenTooltip 487
#define IDS_DebuggerCallstackWindowAsyncFramesVisibleTooltip 488
#define IDS_DebuggerCallstackAsyncHidden 489
#define IDS_DebuggerCallstackAsyncTransitionLabel 490
#define IDS_DebuggerContinueButtonTooltip 491
#define IDS_DebuggerCallstackUnknownSourceLocation 492
#define IDS_DebuggerCallstackEventBreakpoint 493
#define IDS_DebuggerEventListTypicalEvents 494
#define IDS_DebuggerEventListMouseEvents 495
#define IDS_DebuggerEventListKeyboardEvents 496
#define IDS_DebuggerEventListPointerEvents 497
#define IDS_DebuggerEventListTimer 498
#define IDS_DebuggerEventListMouse 499
#define IDS_DebuggerEventListKeyboard 500
#define IDS_DebuggerEventListPointer 501
#define IDS_DebuggerEventListFocus 502
#define IDS_DebuggerEventListMisc 503
#define IDS_DebuggerEventListWindow 504
#define IDS_DebuggerEventListControl 505
#define IDS_DebuggerEventListDevice 506
#define IDS_DebuggerEventListMedia 507
#define IDS_DebuggerEventListGamePad 512
#define IDS_DebuggerJustMyCodeDisabledTooltip 513
#define IDS_DebuggerGoToDefinition 514
#define IDS_DebuggerFindAllReferences 515
#define IDS_DebuggerFindResultsButtonOnTooltip 516
#define IDS_DebuggerFindResultsButtonOffTooltip 517
#define IDS_DebuggerFindResultsTitle 518
#define IDS_DebuggerPreviousResultButtonTooltip 520
#define IDS_DebuggerNextResultButtonTooltip 521
#define IDS_DebuggerClearResultsButtonTooltip 522
#define IDS_DebuggerFindResultsTotals 523
#define IDS_DebuggerCloseFindResultsWindowButtonTooltip 524
#define IDS_DebuggerPinFindResultsWindowButtonTooltip 525
#define IDS_DebuggerUnpinFindResultsWindowButtonTooltip 526
#define IDS_DebuggerDocumentPositionFormat 527
#define IDS_DebuggerGoToLineCommand 528
#define IDS_DebuggerBreakpointsContextMenuCopyLocation 529
#define IDS_DebuggerCallstackInternalFrame 531
#define IDS_DebuggerFullstopSeparatedStrings 532
#define IDS_DebuggerWebStorageGridKeyLabel 533
#define IDS_DebuggerWebStorageGridValueLabel 534
#define IDS_DebuggerWatchesSourceMappedWatchTooltip 535
#define IDS_DebuggerLocalStorageLabel 536
#define IDS_DebuggerSessionStorageLabel 537
#define IDS_DebuggerCookiesGridNameLabel 538
#define IDS_DebuggerCookiesGridValueLabel 539
#define IDS_DebuggerCookiesGridDomainLabel 540
#define IDS_DebuggerCookiesGridPathLabel 541
#define IDS_DebuggerCookiesGridExpiresLabel 542
#define IDS_DebuggerCookiesGridHTTPLabel 543
#define IDS_DebuggerCookiesGridSecureLabel 544
#define IDS_DebuggerCookiesLabel 545
#define IDS_DebuggerCookiesGridDeleteAll 546
#define IDS_DebuggerCookiesGridDeleteAllSession 547
#define IDS_DebuggerCookiesGridCopyToClipboard 548
#define IDS_DebuggerWatchesContextMenuBreakOnObject 549
#define IDS_DebuggerWatchesContextMenuBreakOnProperty 550
#define IDS_DebuggerSourceEditError 551
#define IDS_DebuggerFailedToApplyEditsPrefix 552
#define IDS_DebuggerEditorTooltipOpenLink 553
#define IDS_DebuggerEditorContextMenuOpenLink 554
#define IDS_DebuggerSourceMapButtonTooltip 555
#define IDS_DebuggerWordWrapButtonTooltip 556
#define IDS_DebuggerXHRBreakpointDescription 557
#define IDS_DebuggerXHRCallstackEventDiscription 558
#define IDS_DebuggerBreakpointsAddXHRButtonTooltip 559
#define IDS_DebuggerWatchesWindowTooltip 560
#define IDS_DebuggerCallstackWindowTooltip 561
#define IDS_DebuggerBreakpointsWindowTooltip 562
#define IDS_DebuggerEventXHRBreakpointLabel 563
#define IDS_DebuggerReadOnlyTooltip 564
#define IDS_DebuggerSaveTooltip 565
#define IDS_DebuggerSaveAndRedirectTooltip 566
#define IDS_DebuggerRedirectOffTooltip 567
#define IDS_DebuggerRedirectOnTooltip 568
#define IDS_DebuggerDiffOffTooltip 569
#define IDS_DebuggerDiffOnToolip 570
#define IDS_DebuggerInconsistentChangesApplied 571
#define IDS_DebuggerInconsistentChangesApplied_0 572
#define IDS_DebuggerSaveSucceeded 573
#define IDS_DebuggerSaveAndRedirectSucceeded 574
#define IDS_DebuggerMainThreadLabel 576
#define IDS_DebuggerSaveButton 577
#define IDS_DebuggerErrorOccurred 579
#define IDS_DebuggerDeleteAllCookies 580
#define IDS_DebuggerDeleteAllSessionCookies 581
#define IDS_DebuggerDeleteCookie 582
#define IDS_DebuggerDisconnected 583
#define IDS_DebuggerConnected 584
#define IDS_DebuggerHTTPOnly 585
#define IDS_DebuggerSession 586
#define IDS_DebuggerReadOnly 587
#define IDS_DebuggerDocHasPendingEditsNoBreakpoint 588
#define IDS_DebuggerNoBreakpointFotPreviewDocs 589
#define IDS_DebuggerCannotSaveWhileExecPaused 590
#define IDS_DebuggerCannotSaveWhilePrettyPrintOn 591
#define IDS_DebuggerCannotSavePreviewDocument 592
#define IDS_DebuggerSimulateReachingStorageLimit 593
#define IDS_DebuggerHideResults 594
#define IDS_DebuggerShowResults 595
#define IDS_DebuggerReferences 596
#define IDS_DebuggerSourceMappingDisabled 597
#define IDS_DebuggerMarkAsLibraryCode 598
#define IDS_DebuggerAsmJsDisabled 599
#define IDS_DebuggerAsmJsCompileFailed 600
#define IDS_CommonAttributesTabButtonText 601
#define IDS_CommonBorderLabel 602
#define IDS_CommonCopyAllMenuText 606
#define IDS_CommonCopyItemMenuText 607
#define IDS_CommonCopyMenuText 608
#define IDS_CommonEmptyTextNode 610
#define IDS_CommonFilterDisplayAllMenuText 611
#define IDS_CommonFilterErrorsMenuText 612
#define IDS_CommonFilterMenuText 613
#define IDS_CommonFilterMessagesMenuText 614
#define IDS_CommonFilterWarningsMenuText 615
#define IDS_CommonLayoutTabButtonText 617
#define IDS_CommonMarginLabel 618
#define IDS_CommonMultiError 619
#define IDS_CommonMultiMessage 620
#define IDS_CommonMultiWarning 621
#define IDS_CommonNotAttached 622
#define IDS_CommonOffsetLabel 623
#define IDS_CommonPaddingLabel 624
#define IDS_CommonRunScriptButtonText 625
#define IDS_CommonSingleError 626
#define IDS_CommonSingleMessage 627
#define IDS_CommonSingleWarning 628
#define IDS_CommonStylesTabButtonText 629
#define IDS_CommonTraceStylesTabButtonText 631
#define IDS_CommonOnAttach 632
#define IDS_CommonOnDetach 633
#define IDS_CommonAttributesTabButtonTooltip 634
#define IDS_CommonLayoutTabButtonTooltip 635
#define IDS_CommonSelectElementButtonTooltip 636
#define IDS_CommonStylesTabButtonTooltip 638
#define IDS_CommonTraceStylesTabButtonTooltip 639
#define IDS_CommonWrongDocumentMode 640
#define IDS_CommonSelectElementButton 655
#define IDS_CommonColorPickerButton 656
#define IDS_CommonColorPickerHueLabel 657
#define IDS_CommonColorPickerSaturationLabel 658
#define IDS_CommonColorPickerLightnessLabel 659
#define IDS_CommonColorPickerOpacityLabel 660
#define IDS_CommonAddAttributeButton 661
#define IDS_CommonAddAttributeButtonTooltip 662
#define IDS_CommonAttributeNodeLabel 663
#define IDS_CommonAttributeNodeLabelTooltip 664
#define IDS_CommonRemoveAttributeButton 665
#define IDS_CommonRemoveAttributeButtonTooltip 666
#define IDS_CommonAddAttributeMenuText 667
#define IDS_CommonDeleteElement 668
#define IDS_CommonTextElement 669
#define IDS_CommonShowAll 670
#define IDS_CommonDocTypeElement 671
#define IDS_CommonCommentElement 672
#define IDS_CommonRefreshDomExplorerButton 675
#define IDS_CommonRefreshDomExplorerButtonTooltip 676
#define IDS_CommonCDContextChanged 677
#define IDS_CommonLoadingText 678
#define IDS_CommonClearAttributeButton 679
#define IDS_CommonClearAttributeButtonTooltip 680
#define IDS_CommonUnsupportedBrowser 681
#define IDS_CommonCutMenuText 682
#define IDS_CommonPasteMenuText 683
#define IDS_CommonPasteAsChildMenuText 684
#define IDS_CommonPasteBeforeMenuText 685
#define IDS_CommonDiagnosticsDisabled 690
#define IDS_CommonWrongDocumentModeMetaTag 694
#define IDS_CommonConsoleScriptError 695
#define IDS_CommonDomExplorerScriptError 696
#define IDS_CommonDebuggerScriptError 697
#define IDS_CommonScriptErrorColumn 698
#define IDS_CommonScriptErrorFile 699
#define IDS_CommonScriptErrorLine 700
#define IDS_CommonScriptErrorMessage 701
#define IDS_CommonFilterLogMenuText 706
#define IDS_CommonMatchCaseText 707
#define IDS_CommonSearchContentText 708
#define IDS_CommonSearchDirectionOptionsText 709
#define IDS_CommonSearchFindText 710
#define IDS_CommonSearchNextText 711
#define IDS_CommonSearchOptionsText 712
#define IDS_CommonSearchPrevText 713
#define IDS_CommonSearchSelectorText 714
#define IDS_CommonSearchTypeOptionsText 715
#define IDS_CommonSearchTypeTooltip 716
#define IDS_CommonEventFullScriptPositionText 717
#define IDS_CommonEventFunctionNameText 718
#define IDS_CommonEventScriptPositionText 719
#define IDS_CommonEventsTabButtonText 720
#define IDS_CommonEventsTabButtonTooltip 721
#define IDS_CommonGoToSourceMenuText 722
#define IDS_CommonPagingShowAllText 723
#define IDS_CommonPagingText 724
#define IDS_CommonSetBreakpointMenuText 725
#define IDS_CommonViewAsHtmlMenuText 726
#define IDS_CommonViewAsObjectMenuText 727
#define IDS_CommonConsoleNotLoaded 728
#define IDS_CommonDomExplorerNotLoaded 729
#define IDS_CommonInvalidElementArgument 730
#define IDS_CommonConsoleOccurrences 731
#define IDS_CommonRemoveStyleMenuText 732
#define IDS_CommonEventHandlerTooltip 733
#define IDS_CommonExternalEventHandlerTooltip 736
#define IDS_CommonDynamicScriptBlockEventHandlerToolTip 738
#define IDS_CommonEvalCodeEventHandlerToolTip 739
#define IDS_CommonFunctionCodeEventHandlerToolTip 740
#define IDS_CommonConsoleObjectNotFoundError 746
#define IDS_CommonModifiedEvalFunction 751
#define IDS_CommonModifiedExecScriptFunction 752
#define IDS_CommonDOMExplorerFindBoxHinting 753
#define IDS_CommonDOMSearchBoxToolTip 754
#define IDS_CommonDOMSearchNextButtonToolTip 755
#define IDS_CommonDOMSearchPreviousButtonToolTip 756
#define IDS_CommonConsoleTimerWarning 757
#define IDS_CommonConsoleTimerDisplay 758
#define IDS_CommonNonExistentConsoleTimerWarning 759
#define IDS_CommonCSSTraceStyles 779
#define IDS_CommonDeleteWatchTooltip 788
#define IDS_CommonDOMExplorerComputedStylesNoResultsMessage 790
#define IDS_CommonDOMExplorerComputedStylesAllStyles 791
#define IDS_CommonInlineStyleSelector 792
#define IDS_CommonEmulationCommandsSingleTouchMode 793
#define IDS_CommonEmulationCommandsPinchMode 794
#define IDS_CommonEmulationCommandsRotateLeft 795
#define IDS_CommonEmulationCommandsRotateRight 796
#define IDS_CommonEmulationCommandsGeolocation 797
#define IDS_CommonEmulationCommandsWindowSize 798
#define IDS_CommonEmulationModesDefaultMode 799
#define IDS_CommonEmulationModesCompatMode 800
#define IDS_CommonEmulationModesPhoneMode 802
#define IDS_CommonEmulationModesCustomMode 803
#define IDS_CommonConsoleClearInputButtonTooltip 805
#define IDS_CommonConsoleCssError 806
#define IDS_CommonConsoleSelectError 807
#define IDS_CommonComputedStylesTabButtonText 808
#define IDS_CommonComputedStylesTabButtonTooltip 809
#define IDS_CommonConsoleSelectNotInitializedError 810
#define IDS_CommonConsoleUnsupportedDocumentModeError 811
#define IDS_CommonConsoleUnsupportedDocumentModeAPIError 812
#define IDS_CommonConsoleTooltip 813
#define IDS_CommonDomTooltip 814
#define IDS_CommonDOMExplorerInheritedFromText 815
#define IDS_CommonConsoleToolLabelText 816
#define IDS_CommonDomToolLabelText 817
#define IDS_CommonEmulationTitle 818
#define IDS_CommonEmulationModeSection 819
#define IDS_CommonEmulationDocMode 820
#define IDS_CommonEmulationBrowserMode 821
#define IDS_CommonEmulationUAString 822
#define IDS_CommonEmulationDisplaySection 823
#define IDS_CommonEmulationOrientation 824
#define IDS_CommonEmulationFontScale 825
#define IDS_CommonEmulationResolution 826
#define IDS_CommonEmulationGeoLocationSection 827
#define IDS_CommonEmulationSimulateGPS 828
#define IDS_CommonEmulationGPSOff 829
#define IDS_CommonEmulationGPSOn 830
#define IDS_CommonEmulationGPSOnNoSignal 831
#define IDS_CommonEmulationLatitude 832
#define IDS_CommonEmulationLongitude 833
#define IDS_CommonRefreshStyleMenuText 834
#define IDS_CommonEmulationModesEdgeMode 835
#define IDS_CommonEmulationModesDesktopMode 836
#define IDS_CommonFormatterInternalError 837
#define IDS_CommonFormatterEmbededJSInternalError 838
#define IDS_CommonEditAsHtmlMenuText 840
#define IDS_CommonEmulationCustomUAStringInfo 841
#define IDS_CommonEmulationCustomUAStringLabel 842
#define IDS_CommonEmulationCustom 843
#define IDS_CommonEmulationDefault 844
#define IDS_CommonStyleRuleFileTooltip 845
#define IDS_CommonEllipsis 846
#define IDS_CommonAddToWatch 847
#define IDS_CommonEmulationOrientationLandscape 848
#define IDS_CommonEmulationOrientationPortrait 849
#define IDS_CommonEmulationNoResolutionError 850
#define IDS_CommonEmulationNonNumericValueError 851
#define IDS_CommonEmulationLatitudeError 852
#define IDS_CommonEmulationLongitudeError 853
#define IDS_CommonEmulationInches 854
#define IDS_CommonEmulationPixels 855
#define IDS_CommonEmulationCustomResolution 856
#define IDS_CommonEmulationDisplaySize 857
#define IDS_CommonEmulationWidth 858
#define IDS_CommonEmulationHeight 859
#define IDS_CommonEmulationResolutionLessThanZeroError 860
#define IDS_CommonShowLayoutBoxesButtonTooltip 861
#define IDS_CommonViewSourceMenuText 862
#define IDS_CommonCopyElementWithStylesMenuText 863
#define IDS_CommonShowLayoutBoxesButtonTooltipWithShortcut 864
#define IDS_CommonRefreshDomExplorerButtonTooltipWithShortcut 865
#define IDS_CommonAllStylesDomExplorerButtonTooltipOn 866
#define IDS_CommonAllStylesDomExplorerButtonTooltipOff 867
#define IDS_CommonAccessKeyCtrlX 870
#define IDS_CommonAccessKeyCtrlC 871
#define IDS_CommonAccessKeyCtrlV 872
#define IDS_CommonAccessKeyDel 873
#define IDS_CommonAriaOverridden 874
#define IDS_CommonRunScriptButtonTextMultiLine 875
#define IDS_CommonAccessKeyCtrlEnter 876
#define IDS_CommonAccessKeyCtrlF9 880
#define IDS_CommonAccessKeyCtrlShiftF10 881
#define IDS_CommonAccessKeyCtrlF10 882
#define IDS_CommonAccessKeyCtrlW 883
#define IDS_CommonAccessKeyCtrlF4 884
#define IDS_CommonAccessKeyAltNumStar 885
#define IDS_CommonPseudoClassHoverTooltip 886
#define IDS_CommonPseudoClassHover 887
#define IDS_CommonPseudoClassVisitedTooltip 888
#define IDS_CommonPseudoClassVisited 889
#define IDS_CommonPseudoClassesButtonTooltipOn 890
#define IDS_CommonPseudoClassesButtonTooltipOff 891
#define IDS_CommonPausedAtABreakpoint 892
#define IDS_CommonRevertStyleMenuText 896
#define IDS_CommonChangesTabButtonText 897
#define IDS_CommonChangesTabButtonTooltip 898
#define IDS_CommonChangesViewUnknownCSSSource 899
#define IDS_CommonChangesViewNewInSessionCSSSource 900
#define IDS_CommonChangesViewCSSFileLinkLineAndColumn 901
#define IDS_CommonChangesViewCSSFileLinkLine 902
#define IDS_CommonEmulationModesEnterpriseMode 903
#define IDS_CommonChangesViewEmptyMessage 904
#define IDS_CommonHelpButtonTooltip 905
#define IDS_CommonCloseButtonTooltip 906
#define IDS_CommonEditAttributeNameAriaLabel 907
#define IDS_CommonEditAttributeValueAriaLabel 908
#define IDS_CommonalwaysBufferConsoleText 909
#define IDS_CommonalwaysBufferConsoleEnable 910
#define IDS_CommonalwaysBufferConsoleDoNotShowAgain 911
#define IDS_CommonAriaChangeStateRemove 912
#define IDS_CommonAriaChangeStateAdd 913
#define IDS_CommonAriaChangeStateUpdate 914
#define IDS_CommonDisabled 915
#define IDS_CommonAccessKeyAltF9 916
#define IDS_CommonAccessKeyF9 917
#define IDS_CommonDOMExplorerComputedStylesFilterTextBoxPlaceholder 918
#define IDS_CommonAddPropertyMenuText 919
#define IDS_CommonAddRuleMenuText 920
#define IDS_CommonCopyPropertyMenuText 921
#define IDS_CommonCopyRuleMenuText 922
#define IDS_CommonEmulationLargeDisplaySizeError 928
#define IDS_CommonEmulationLargeResolutionWidthError 929
#define IDS_CommonEmulationLargeResolutionHeightError 930
#define IDS_CommonEmulationDeleteButtonTooltip 932
#define IDS_CommonEmulationToolLabelText 933
#define IDS_CommonEmulationResetButtonTooltip 936
#define IDS_CommonConsoleStaleMessage 937
#define IDS_CommonConsoleNavigationSeparatorLabel 940
#define IDS_CommonEmulationInvalidValueResolutionError 941
#define IDS_CommonClearButtonText 942
#define IDS_CommonClearMenuText 943
#define IDS_CommonColorPickerButtonTooltip 944
#define IDS_CommonEyedropperButtonTooltip 946
#define IDS_CommonRibbonControlNextButtonTooltip 948
#define IDS_CommonRibbonControlPreviousButtonTooltip 949
#define IDS_CommonColorPickerPaletteTooltip 950
#define IDS_CommonHue 951
#define IDS_CommonSaturation 952
#define IDS_CommonLightness 953
#define IDS_CommonAlpha 954
#define IDS_CommonTargetSelectorLabel 960
#define IDS_CommonAccessKeyCtrlD 961
#define IDS_CommonAccessKeyCtrlShiftD 962
#define IDS_CommonAccessKeyCtrlG 963
#define IDS_CommonSelectInDom 964
#define IDS_CommonToggleToSingleLineTooltip 965
#define IDS_CommonToggleToMultiLineTooltip 966
#define IDS_CommonResourceGridEditItem 967
#define IDS_CommonResourceGridRemoveItem 968
#define IDS_CommonResourceGridRefresh 969
#define IDS_CommonDomColorPickerButtonTooltip 970
#define IDS_CommonSlidersButtonTooltip 971
#define IDS_CommonShowLayoutButtonTooltipWithShortcut 972
#define IDS_CommonUserStylesDomExplorerButtonTooltip 973
#define IDS_CommonClearOnNavigate 974
#define IDS_CommonEmulationPersistSettingsButtonTooltip 975
#define IDS_CommonZoomDialogCurrentLevel 976
#define IDS_CommonZoomDialogShortcutInfo 977
#define IDS_CommonConsoleInputTooltipSingleLine 978
#define IDS_CommonConsoleInputTooltipMultiLine 979
#define IDS_CommonConsoleTooManyMessagesError 980
#define IDS_CommonSearchBoxTooltip 981
#define IDS_CommonSearchBoxPlaceholder 982
#define IDS_CommonByteUnits 983
#define IDS_CommonGigabyteUnits 984
#define IDS_CommonKilobyteUnits 985
#define IDS_CommonMegabyteUnits 986
#define IDS_CommonEnabled 992
#define IDS_CommonGotDisabled 993
#define IDS_CommonDeleteItem 994
#define IDS_CommonAccessKeyCtrlShiftDel 995
#define IDS_CommonAccessKeyCtrlDel 996
#define IDS_CommonAccessKeyCtrlF5 997
#define IDS_CommonNoLongerAttachedToDOM 998
#define IDS_CommonCopySelectedItems 999
#define IDS_CommonSelectAll 1000
#define IDS_CommonAccessKeyCtrlA 1001
#define IDS_CommonWindows10MobileMode 1002
#define IDS_MemoryAnalyzerErrorWhileProcessing 2001
#define IDS_MemoryAnalyzerTakeSnapshot 2002
#define IDS_MemoryAnalyzerProcessingSnapshot 2004
#define IDS_MemoryAnalyzerReferenceGraph 2005
#define IDS_MemoryAnalyzerSummary 2006
#define IDS_MemoryAnalyzerPrivateBytes 2009
#define IDS_MemoryAnalyzerJavaScriptHeapSize 2010
#define IDS_MemoryAnalyzerTotalObjectSize 2011
#define IDS_MemoryAnalyzerNumberOfObjects 2012
#define IDS_MemoryAnalyzerNumberOfTypes 2013
#define IDS_MemoryAnalyzerJavaScriptObjects 2014
#define IDS_MemoryAnalyzerExternalObjects 2017
#define IDS_MemoryAnalyzerHeapSizeLinkTooltip 2018
#define IDS_MemoryAnalyzerObjectsCountLinkTooltip 2019
#define IDS_MemoryAnalyzerHeapSizeDiffLinkTooltip 2020
#define IDS_MemoryAnalyzerObjectsCountDiffLinkTooltip 2021
#define IDS_MemoryAnalyzerCompareTo 2022
#define IDS_MemoryAnalyzerHeapSnapshot 2023
#define IDS_MemoryAnalyzerGeneratingComparisonView 2024
#define IDS_MemoryAnalyzerIdentifiers 2025
#define IDS_MemoryAnalyzerRetainedSize 2026
#define IDS_MemoryAnalyzerCount 2027
#define IDS_MemoryAnalyzerSizeDiff 2029
#define IDS_MemoryAnalyzerRetainedSizeDiff 2030
#define IDS_MemoryAnalyzerType 2031
#define IDS_MemoryAnalyzerSize 2033
#define IDS_MemoryAnalyzerSnapshotNumber 2034
#define IDS_MemoryAnalyzerSnapshotNumberDiff 2035
#define IDS_MemoryAnalyzerdominators 2036
#define IDS_MemoryAnalyzerDOM 2037
#define IDS_MemoryAnalyzerroots 2038
#define IDS_MemoryAnalyzertypes 2039
#define IDS_MemoryAnalyzerwinrt 2040
#define IDS_MemoryAnalyzerCompareToTooltip 2043
#define IDS_MemoryAnalyzerCountTooltip 2044
#define IDS_MemoryAnalyzerDOMTooltip 2047
#define IDS_MemoryAnalyzerIdentifiersTooltip 2049
#define IDS_MemoryAnalyzerRetainedSizeDiffTooltip 2050
#define IDS_MemoryAnalyzerRetainedSizeTooltip 2051
#define IDS_MemoryAnalyzerSizeDiffTooltip 2053
#define IDS_MemoryAnalyzerSizeTooltip 2054
#define IDS_MemoryAnalyzerSnapshotTabTooltip 2055
#define IDS_MemoryAnalyzerTakeSnapshotTooltip 2057
#define IDS_MemoryAnalyzerwinrtTooltip 2060
#define IDS_MemoryAnalyzerApproximateSizeTooltip 2061
#define IDS_MemoryAnalyzerCouldNotGetHeapSizeTooltip 2062
#define IDS_MemoryAnalyzerExternalObjectsTooltip 2063
#define IDS_MemoryAnalyzerHeapSizeTooltip 2064
#define IDS_MemoryAnalyzerJavaScriptObjectsTooltip 2065
#define IDS_MemoryAnalyzerMarkupElementsTooltip 2066
#define IDS_MemoryAnalyzerNumberOfObjectsTooltip 2067
#define IDS_MemoryAnalyzerNumberOfTypesTooltip 2068
#define IDS_MemoryAnalyzerPrivateBytesTooltip 2069
#define IDS_MemoryAnalyzerTotalObjectSizeTooltip 2071
#define IDS_MemoryAnalyzerWinRTObjectsTooltip 2072
#define IDS_MemoryAnalyzerWarningIncompatibleStandardsModeVS 2073
#define IDS_MemoryAnalyzerWarningNotAttached 2074
#define IDS_MemoryAnalyzerObjectsCount 2086
#define IDS_MemoryAnalyzerBaseline 2087
#define IDS_MemoryAnalyzerNoDiff 2088
#define IDS_MemoryAnalyzerHubGraphHeapLegend 2089
#define IDS_MemoryAnalyzerHubGraphHeapUnits 2090
#define IDS_MemoryAnalyzerHubGraphSnapshotLegend 2091
#define IDS_MemoryAnalyzerHubGraphUserMarkLegend 2092
#define IDS_MemoryAnalyzerHubTimelineDescription 2093
#define IDS_MemoryAnalyzerHubTimelineTitle 2094
#define IDS_MemoryAnalyzerHubToolDescription 2095
#define IDS_MemoryAnalyzerHubToolName 2096
#define IDS_MemoryAnalyzerCompareButtonTooltipText 2097
#define IDS_MemoryAnalyzerSnapshotCreationFailed 2098
#define IDS_MemoryAnalyzerHeapSize 2099
#define IDS_MemoryAnalyzerDisplayObjectIDs 2100
#define IDS_MemoryAnalyzerShowBuiltIns 2101
#define IDS_MemoryAnalyzerScreenshot 2102
#define IDS_MemoryAnalyzerByteUnits 2104
#define IDS_MemoryAnalyzerGigabyteUnits 2105
#define IDS_MemoryAnalyzerKilobyteUnits 2106
#define IDS_MemoryAnalyzerMegabyteUnits 2107
#define IDS_MemoryAnalyzerF12ToolTitle 2108
#define IDS_MemoryAnalyzerRulerMarkTooltipLabel 2113
#define IDS_MemoryAnalyzerRulerAriaLabel 2114
#define IDS_MemoryAnalyzerRulerLeftSliderAriaLabel 2115
#define IDS_MemoryAnalyzerRulerRightSliderAriaLabel 2116
#define IDS_MemoryAnalyzerRulerSliderAriaValueText 2117
#define IDS_MemoryAnalyzerRulerLifecycleMarkLabel 2118
#define IDS_MemoryAnalyzerRulerUserMarkLabel 2119
#define IDS_MemoryAnalyzerRulerMarkLabel 2120
#define IDS_MemoryAnalyzerRulerTitle 2121
#define IDS_MemoryAnalyzerMillisecondsLabel 2122
#define IDS_MemoryAnalyzerMinutesLabel 2123
#define IDS_MemoryAnalyzerSecondsLabel 2124
#define IDS_MemoryAnalyzerMinutesAbbreviation 2125
#define IDS_MemoryAnalyzerMillisecondsAbbreviation 2126
#define IDS_MemoryAnalyzerSecondsAbbreviation 2127
#define IDS_MemoryAnalyzerSwimlaneCollapseAriaLabel 2128
#define IDS_MemoryAnalyzerSwimlaneExpandAriaLabel 2129
#define IDS_MemoryAnalyzerToolbarZoomInButton 2130
#define IDS_MemoryAnalyzerGraphTitle 2136
#define IDS_MemoryAnalyzerShowInRootsViewLabel 2137
#define IDS_MemoryAnalyzerDetachedDomNodeWarning 2138
#define IDS_MemoryAnalyzerDetachedDomNodeDisposableWarning 2139
#define IDS_MemoryAnalyzerDetachedDomNodeTooltip 2140
#define IDS_MemoryAnalyzerDetachedDomNodeDisposableTooltip 2141
#define IDS_MemoryAnalyzerReachedItemsCapMessage 2142
#define IDS_MemoryAnalyzerChildrenLoadNext 2143
#define IDS_MemoryAnalyzerERRoutOfMemory 2146
#define IDS_MemoryAnalyzerERRbadHexDigit 2147
#define IDS_MemoryAnalyzerERRbadNumber 2148
#define IDS_MemoryAnalyzerERRillegalChar 2149
#define IDS_MemoryAnalyzerERRnoColon 2150
#define IDS_MemoryAnalyzerERRnoRbrack 2151
#define IDS_MemoryAnalyzerERRnoRcurly 2152
#define IDS_MemoryAnalyzerERRnoStrEnd 2153
#define IDS_MemoryAnalyzerERRsyntax 2154
#define IDS_MemoryAnalyzerERRmissingObjectId 2155
#define IDS_MemoryAnalyzerERRinvalidObjectID 2156
#define IDS_MemoryAnalyzerERRunknownError 2157
#define IDS_MemoryAnalyzerMemoryTooltip 2158
#define IDS_MemoryAnalyzerMemoryDisabledAtBreakpoint 2159
#define IDS_MemoryAnalyzerDiffColumnOperationAdded 2160
#define IDS_MemoryAnalyzerDiffColumnOperationModified 2161
#define IDS_MemoryAnalyzerDiffColumnOperationUnchanged 2162
#define IDS_MemoryAnalyzerDiffColumnOperationHeader 2163
#define IDS_MemoryAnalyzerDisplayCircularReferences 2164
#define IDS_MemoryAnalyzerTriggerGC 2176
#define IDS_MemoryAnalyzerTooltipTimeLabel 2177
#define IDS_MemoryAnalyzerTooltipValueLabel 2178
#define IDS_MemoryAnalyzerScopeFilterTooltip 2179
#define IDS_MemoryAnalyzerScopeFilterLabel 2180
#define IDS_MemoryAnalyzerScopeObjectsAddedBetweenSnapshots 2181
#define IDS_MemoryAnalyzerScopeObjectsLeftFromPreviousSnapshot 2182
#define IDS_MemoryAnalyzerScopeAllObjects 2183
#define IDS_MemoryAnalyzerTakeSnapshotShortcut 2184
#define IDS_MemoryAnalyzerRulerAggregatedMarks 2185
#define IDS_MemoryAnalyzerDetachedDomNodeTypeObjectTooltip 2186
#define IDS_MemoryAnalyzerShowInDominatorsViewLabel 2187
#define IDS_MemoryAnalyzerDiffColumnOperationHeaderTooltip 2188
#define IDS_MemoryAnalyzerF12StartButtonTooltip 2189
#define IDS_MemoryAnalyzerF12StopButtonTooltip 2190
#define IDS_MemoryAnalyzerF12SnapshotButtonTooltip 2191
#define IDS_MemoryAnalyzerF12StartProfilingMessage 2192
#define IDS_MemoryAnalyzerSettingsMenuButtonTooltipText 2193
#define IDS_MemoryAnalyzerSourceInfoIdentifierLabel 2194
#define IDS_MemoryAnalyzerSourceInfoFileLabel 2195
#define IDS_MemoryAnalyzerSourceInfoLineLabel 2196
#define IDS_MemoryAnalyzerSourceInfoColumnLabel 2197
#define IDS_MemoryAnalyzerSummaryTabTooltip 2198
#define IDS_MemoryAnalyzertypesTooltip 2199
#define IDS_MemoryAnalyzerTypeTooltip 2200
#define IDS_MemoryAnalyzerrootsTooltip 2201
#define IDS_MemoryAnalyzerIdentifierFilterTooltip 2202
#define IDS_MemoryAnalyzerdominatorsTooltip 2203
#define IDS_MemoryAnalyzerObjectIdNotFound 2204
#define IDS_MemoryAnalyzerEnterKey 2205
#define IDS_MemoryAnalyzerUnableToViewSource 2206
#define IDS_MemoryAnalyzerViewSourceLabel 2207
#define IDS_MemoryAnalyzerShowNonMatchingReferences 2208
#define IDS_MemoryAnalyzerFoldObjectsByDominator 2209
#define IDS_MemoryAnalyzerHasDetachedDomNodeChildrenTooltip 2210
#define IDS_MemoryAnalyzerDetachedDomNodeRetainingTypeObjectTooltip 2211
#define IDS_MemoryAnalyzerCircularReferenceMarker 2212
#define IDS_MemoryAnalyzerCircularReferenceMessage 2213
#define IDS_MemoryAnalyzerFoldInObjectsByDominatorTooltip 2214
#define IDS_MemoryAnalyzerPotentialIssuesTooltip 2215
#define IDS_MemoryAnalyzerF12OpenSessionButtonTooltip 2216
#define IDS_MemoryAnalyzerF12SaveSessionButtonTooltip 2217
#define IDS_MemoryAnalyzerOpenSessionFailedMessage 2218
#define IDS_MemoryAnalyzerSaveSessionFailedMessage 2219
#define IDS_MemoryAnalyzerIdentifierFilter 2220
#define IDS_MemoryAnalyzerProcessingSnapshotCompleted 2221
#define IDS_MemoryAnalyzerShowInDomExplorerLabel 2224
#define IDS_MemoryAnalyzerViewSnapshotDetails 2225
#define IDS_MemoryAnalyzerCompareToEllipsis 2226
#define IDS_MemoryAnalyzerUserMarkTooltip 2227
#define IDS_MemoryAnalyzerLoading 2228
#define IDS_MemoryAnalyzerWarningIncompatibleStandardsModeF12 2229
#define IDS_VisualProfilerAFG_Legend 3001
#define IDS_VisualProfilerAFG_Title 3002
#define IDS_VisualProfilerAFG_Unit 3003
#define IDS_VisualProfilerAnalyzeDataStatus 3004
#define IDS_VisualProfilerCPUChartTitle 3005
#define IDS_VisualProfilerCPUTooltipCategoryLabel 3006
#define IDS_VisualProfilerCPUTooltipUtilizationLabel 3007
#define IDS_VisualProfilerDurationLabelInclusive 3008
#define IDS_VisualProfilerGC_Category 3009
#define IDS_VisualProfilerGCLegendTooltip 3010
#define IDS_VisualProfilerGenericDataProcessingError 3011
#define IDS_VisualProfilerHubGraphHeapLegend 3012
#define IDS_VisualProfilerHubTimelineCPUDescription 3013
#define IDS_VisualProfilerHubTimelineCPUTitle 3014
#define IDS_VisualProfilerHubToolDescription 3015
#define IDS_VisualProfilerHubToolName 3016
#define IDS_VisualProfilerImageDecoding_Category 3017
#define IDS_VisualProfilerImageDecodingLegendTooltip 3018
#define IDS_VisualProfilerRulerLifecycleMarkLabel 3019
#define IDS_VisualProfilerRulerUserMarkLabel 3020
#define IDS_VisualProfilerLoading_Category 3021
#define IDS_VisualProfilerLoadingLegendTooltip 3022
#define IDS_VisualProfilerMillisecondsAbbreviation 3023
#define IDS_VisualProfilerRendering_Category 3024
#define IDS_VisualProfilerRenderingLegendTooltip 3025
#define IDS_VisualProfilerRuler_LifeCycleEvents 3026
#define IDS_VisualProfilerRuler_UserMarks 3027
#define IDS_VisualProfilerRulerMarkLabel 3028
#define IDS_VisualProfilerScripting_Category 3029
#define IDS_VisualProfilerScriptingLegendTooltip 3030
#define IDS_VisualProfilerSecondsAbbreviation 3031
#define IDS_VisualProfilerStartTimeLabel 3032
#define IDS_VisualProfilerStyling_Category 3033
#define IDS_VisualProfilerStylingLegendTooltip 3034
#define IDS_VisualProfilerTimelineLabel 3035
#define IDS_VisualProfilerTimelineSortDuration 3036
#define IDS_VisualProfilerTimelineSortLabel 3037
#define IDS_VisualProfilerTimelineSortStartTime 3038
#define IDS_VisualProfilerUnknown_Category 3040
#define IDS_VisualProfilerUnknownLegendTooltip 3041
#define IDS_VisualProfilerRulerTitle 3042
#define IDS_VisualProfilerToolbarButtonClearSelection 3043
#define IDS_VisualProfilerToolbarButtonResetZoom 3044
#define IDS_VisualProfilerToolbarButtonZoomIn 3045
#define IDS_VisualProfilerAddressNameLabel 3046
#define IDS_VisualProfilerAtTargetEventPhaseLabel 3047
#define IDS_VisualProfilerBubblingEventPhaseLabel 3048
#define IDS_VisualProfilerCapturingEventPhaseLabel 3049
#define IDS_VisualProfilerDefaultPreventedLabel 3050
#define IDS_VisualProfilerEventNameLabel 3051
#define IDS_VisualProfilerEventPhaseLabel 3052
#define IDS_VisualProfilerImageDecodedLabel 3053
#define IDS_VisualProfilerListenerUsesCaptureLabel 3056
#define IDS_VisualProfilerNoLabel 3057
#define IDS_VisualProfilerPropagationStoppedLabel 3058
#define IDS_VisualProfilerScriptUrlLabel 3059
#define IDS_VisualProfilerStatusCodeLabel 3060
#define IDS_VisualProfilerYesLabel 3062
#define IDS_VisualProfilerTimerTypeLabel 3063
#define IDS_VisualProfilerCssParsingEventDescription 3064
#define IDS_VisualProfilerEvaluatingScriptEventDescription 3065
#define IDS_VisualProfilerHttpRequestEventDescription 3066
#define IDS_VisualProfilerImageDecodedEventDescription 3067
#define IDS_VisualProfilerPaintEventDescription 3068
#define IDS_VisualProfilerTimerFiredEventDescription 3069
#define IDS_VisualProfilerCssCalculation 3070
#define IDS_VisualProfilerCssParsing 3071
#define IDS_VisualProfilerDomEvent 3072
#define IDS_VisualProfilerEvaluatingScript 3073
#define IDS_VisualProfilerEventHandler 3074
#define IDS_VisualProfilerGarbageCollection 3075
#define IDS_VisualProfilerHtmlParsing 3076
#define IDS_VisualProfilerHttpRequest 3077
#define IDS_VisualProfilerImageDecoded 3078
#define IDS_VisualProfilerLayout 3079
#define IDS_VisualProfilerPaint 3080
#define IDS_VisualProfilerTimerFired 3081
#define IDS_VisualProfilerMillisecondsLabel 3082
#define IDS_VisualProfilerMinutesLabel 3083
#define IDS_VisualProfilerRulerMarkTooltipLabel 3084
#define IDS_VisualProfilerSecondsLabel 3085
#define IDS_VisualProfilerMinutesAbbreviation 3086
#define IDS_VisualProfilerAlignedBeat 3087
#define IDS_VisualProfilerAnimationFrame 3088
#define IDS_VisualProfilerHtmlSpeculativeDownloading 3089
#define IDS_VisualProfilerWindowsRuntimeEvent 3090
#define IDS_VisualProfilerWindowsRuntimeAsyncCallback 3091
#define IDS_VisualProfilerEventHeaderLabel 3092
#define IDS_VisualProfilerThreadContextLabel 3094
#define IDS_VisualProfilerUIThreadContext 3095
#define IDS_VisualProfilerRenderLayer 3096
#define IDS_VisualProfilerCPUBarAriaLabel 3097
#define IDS_VisualProfilerCPUGraphAriaLabel 3098
#define IDS_VisualProfilerVisualThroughputGraphAriaLabel 3099
#define IDS_VisualProfilerVisualThroughputStepAriaLabel 3100
#define IDS_VisualProfilerEventsTimelineAriaLabel 3101
#define IDS_VisualProfilerEventsTimelineEventAriaLabel 3102
#define IDS_VisualProfilerRulerAriaLabel 3103
#define IDS_VisualProfilerRulerLeftSliderAriaLabel 3104
#define IDS_VisualProfilerRulerRightSliderAriaLabel 3105
#define IDS_VisualProfilerRulerSliderAriaValueText 3106
#define IDS_VisualProfilerImageUrlLabel 3107
#define IDS_VisualProfilerDurationLabelExclusive 3108
#define IDS_VisualProfilerAlignedBeatEventDescription 3109
#define IDS_VisualProfilerAnimationFrameEventDescription 3110
#define IDS_VisualProfilerCssCalculationEventDescription 3111
#define IDS_VisualProfilerDomEventDescription 3112
#define IDS_VisualProfilerEventHandlerEventDescription 3113
#define IDS_VisualProfilerGarbageCollectionEventDescription 3114
#define IDS_VisualProfilerHtmlParsingEventDescription 3115
#define IDS_VisualProfilerHtmlSpeculativeDownloadingEventDescription 3116
#define IDS_VisualProfilerLayoutEventDescription 3117
#define IDS_VisualProfilerWindowsRuntimeEventDescription 3118
#define IDS_VisualProfilerWindowsRuntimeAsyncCallbackDescription 3119
#define IDS_VisualProfilerGraphCollapseAriaLabel 3120
#define IDS_VisualProfilerGraphExpandAriaLabel 3121
#define IDS_VisualProfilerOriginLabel 3122
#define IDS_VisualProfilerDimensionsLabel 3123
#define IDS_VisualProfilerInlineScriptLabel 3124
#define IDS_VisualProfilerScriptContentPreviewLabel 3125
#define IDS_VisualProfilerRenderLayoutEventDescription 3126
#define IDS_VisualProfilerF12ToolTitle 3127
#define IDS_VisualProfilerTASK_DoEnReNo 3132
#define IDS_VisualProfilerTASK_DoInsElm 3133
#define IDS_VisualProfilerDDTrackDomSet 3134
#define IDS_VisualProfilerTASK_Fi 3135
#define IDS_VisualProfilerTASK_FiCmpFmt 3136
#define IDS_VisualProfilerUnknownTask 3137
#define IDS_VisualProfilerTASK_TableBox 3138
#define IDS_VisualProfilerTASK_SvgCssBox 3139
#define IDS_VisualProfilerTASK_PageFrame 3140
#define IDS_VisualProfilerTASK_DocumentResize 3141
#define IDS_VisualProfilerTASK_TextBlock 3142
#define IDS_VisualProfilerTASK_LineBox 3143
#define IDS_VisualProfilerUnknownElement 3144
#define IDS_VisualProfilerDDTrackerStyleChangeDescription 3145
#define IDS_VisualProfilerDDTrackerStyleComputationDescription 3146
#define IDS_VisualProfilerDDTrackerDOMDescription 3147
#define IDS_VisualProfilerDDTrackerLayoutDescription 3148
#define IDS_VisualProfilerDDTrackerStyleComputationDetailHeader 3149
#define IDS_VisualProfilerDDTrackerStyleChangeDetailHeader 3150
#define IDS_VisualProfilerDDTrackerDomDetailHeader 3151
#define IDS_VisualProfilerDDTrackerLayoutDetailHeader 3152
#define IDS_VisualProfilerDDTrackerElementLabel 3153
#define IDS_VisualProfilerInclusiveTimeDetailsHeader 3154
#define IDS_VisualProfilerUnknownTimerType 3156
#define IDS_VisualProfilerAnimationFrameTimerTypeLabel 3157
#define IDS_VisualProfilerMethodNameLabel 3158
#define IDS_VisualProfilerSourceLocationLabel 3159
#define IDS_VisualProfilerImmediatePropagationStoppedLabel 3160
#define IDS_VisualProfilerEventTargetLabel 3161
#define IDS_VisualProfilerSourceLocationLink 3162
#define IDS_VisualProfilerInclusiveTimeAriaLabel 3163
#define IDS_VisualProfilerDonutSectorAriaLabel 3164
#define IDS_VisualProfilerDOMAccessEvent 3165
#define IDS_VisualProfilerAccessTypeLabel 3166
#define IDS_VisualProfilerTargetElementLabel 3167
#define IDS_VisualProfilerDroppedEventsWarning 3168
#define IDS_VisualProfilerStylesheetUrlLabel 3169
#define IDS_VisualProfilerInlineStylesheetLabel 3170
#define IDS_VisualProfilerInclusiveTimeSVGLabelString 3171
#define IDS_VisualProfilerTimeoutLabel 3172
#define IDS_VisualProfilerVisualProfilerTooltip 3173
#define IDS_VisualProfilerDOMAccessEventHeader 3174
#define IDS_VisualProfilerDurationLabel 3175
#define IDS_VisualProfilerWarningIncompatibleStandardsModeVS 3178
#define IDS_VisualProfilerNavigation 3179
#define IDS_VisualProfilerUnableToNavigateToSource 3180
#define IDS_VisualProfilerLayoutModeLabel 3181
#define IDS_VisualProfilerLifecycleMarkTooltip 3183
#define IDS_VisualProfilerVisualProfilerDisabledAtBreakpoint 3184
#define IDS_VisualProfilerRulerAggregatedMarks 3185
#define IDS_VisualProfilerSwimlaneCollapseAriaLabel 3186
#define IDS_VisualProfilerSwimlaneExpandAriaLabel 3187
#define IDS_VisualProfilerClearSelectionContextMenu 3188
#define IDS_VisualProfilerFilterToEventContextMenu 3189
#define IDS_VisualProfilerDDTrackerSetStyleContextName 3190
#define IDS_VisualProfilerViewSourceLabel 3191
#define IDS_VisualProfilerEnterKey 3192
#define IDS_VisualProfilerSourceInfoFileLabel 3193
#define IDS_VisualProfilerSourceInfoLineLabel 3194
#define IDS_VisualProfilerSourceInfoColumnLabel 3195
#define IDS_VisualProfilerSourceInfoEventLabel 3196
#define IDS_VisualProfilerFilteringMenuButtonTooltipText 3197
#define IDS_VisualProfilerFilterBackgroundActivities 3198
#define IDS_VisualProfilerFilterNetworkActivities 3199
#define IDS_VisualProfilerCallbackFunction 3200
#define IDS_VisualProfilerProfileJustMyCode 3201
#define IDS_VisualProfilerProfileAllCode 3202
#define IDS_VisualProfilerRenderThread 3203
#define IDS_VisualProfilerDownloadThread 3204
#define IDS_VisualProfilerFilterNegligibleUIActivities 3205
#define IDS_VisualProfilerFormatting 3206
#define IDS_VisualProfilerElementFormatting 3207
#define IDS_VisualProfilerTooltipTimeLabel 3208
#define IDS_VisualProfilerTooltipValueLabel 3209
#define IDS_VisualProfilerF12StartButtonTooltip 3210
#define IDS_VisualProfilerF12StopButtonTooltip 3211
#define IDS_VisualProfilerF12StartProfilingMessage 3212
#define IDS_VisualProfilerF12StopProfilingMessage 3213
#define IDS_VisualProfilerImmediateTimerTypeLabel 3214
#define IDS_VisualProfilerIntervalTimerTypeLabel 3215
#define IDS_VisualProfilerTimelineSortTooltip 3216
#define IDS_VisualProfilerTimeoutTimerTypeLabel 3217
#define IDS_VisualProfilerFilterMeasures 3232
#define IDS_VisualProfilerMeasure 3233
#define IDS_VisualProfilerMeasureDescription 3234
#define IDS_VisualProfilerMeasureName 3235
#define IDS_VisualProfilerStartMarkName 3236
#define IDS_VisualProfilerEndMarkName 3237
#define IDS_VisualProfilerFrame 3238
#define IDS_VisualProfilerFilterFrames 3239
#define IDS_VisualProfilerMillisecondsSelectedLabel 3240
#define IDS_VisualProfilerSecondsSelectedLabel 3241
#define IDS_VisualProfilerMinutesSelectedLabel 3242
#define IDS_VisualProfilerEventNameFilterPlaceholder 3243
#define IDS_VisualProfilerEventNameFilterTooltip 3244
#define IDS_VisualProfilerMediaQueryListener 3245
#define IDS_VisualProfilerMediaQueryListenerEventDescription 3246
#define IDS_VisualProfilerMediaQueryLabel 3247
#define IDS_VisualProfilerMutationObserver 3248
#define IDS_VisualProfilerMutationObserverEventDescription 3249
#define IDS_VisualProfilerFilterEvents 3250
#define IDS_VisualProfilerFrameGroupingTooltip 3251
#define IDS_VisualProfilerF12OpenSessionButtonTooltip 3252
#define IDS_VisualProfilerF12SaveSessionButtonTooltip 3253
#define IDS_VisualProfilerOpenSessionFailedMessage 3254
#define IDS_VisualProfilerSaveSessionFailedMessage 3255
#define IDS_VisualProfilerFilterUIActivities 3256
#define IDS_VisualProfilerWrongDataSource 3257
#define IDS_VisualProfilerDurationFilterAll 3258
#define IDS_VisualProfilerDurationFilterTimed 3259
#define IDS_VisualProfilerDurationFilterTooltip 3260
#define IDS_VisualProfilerBackgroundActivityFilterTooltip 3261
#define IDS_VisualProfilerNetworkTrafficFilterTooltip 3262
#define IDS_VisualProfilerUIActivityFilterTooltip 3263
#define IDS_VisualProfilerUserMeasuresFilterTooltip 3264
#define IDS_VisualProfilerSectorTooltipFormat 3266
#define IDS_VisualProfilerIdle 3267
#define IDS_VisualProfilerSelectionDurationLabel 3268
#define IDS_VisualProfilerUIThreadSummaryHeader 3269
#define IDS_VisualProfilerImagePreviewHeader 3270
#define IDS_VisualProfilerCPUTooltipTimeLabel 3280
#define IDS_VisualProfilerFilterImageDecoding 3281
#define IDS_VisualProfilerShowInDomExplorerLabel 3282
#define IDS_VisualProfilerUserMarkTooltip 3283
#define IDS_VisualProfilerWarningIncompatibleStandardsModeF12 3284
#define IDS_VisualProfilerImageDecodingThread 3285
#define IDS_VisualProfilerAsyncStackLabel 3286
#define IDS_VisualProfilerAsyncStackTransition 3287
#define IDS_VisualProfilerTimelineTabLabel 3288
#define IDS_VisualProfilerTimelineTabTooltip 3289
#define IDS_VisualProfilerJavaScriptCallStacksTabLabel 3290
#define IDS_VisualProfilerJavaScriptCallStacksTabTooltip 3291
#define IDS_VisualProfilerCpuUsageTreeGrid_ContextMenu_Copy 3292
#define IDS_VisualProfilerCpuUsageTreeGrid_ContextMenu_ViewSource 3293
#define IDS_VisualProfilerCpuUsageTreeGrid_FunctionNameHeader 3294
#define IDS_VisualProfilerCpuUsageTreeGrid_FunctionNameTooltip 3295
#define IDS_VisualProfilerCpuUsageTreeGrid_ModuleHeader 3296
#define IDS_VisualProfilerCpuUsageTreeGrid_ModuleTooltip 3297
#define IDS_VisualProfilerCpuUsageTreeGrid_PercentageTooltip 3298
#define IDS_VisualProfilerCpuUsageTreeGrid_SamplesTooltip 3299
#define IDS_VisualProfilerCpuUsageTreeGrid_SelfSamplesHeader 3300
#define IDS_VisualProfilerCpuUsageTreeGrid_SelfSamplesHeaderTooltip 3301
#define IDS_VisualProfilerCpuUsageTreeGrid_SelfSamplesPercentHeader 3302
#define IDS_VisualProfilerCpuUsageTreeGrid_SelfSamplesPercentHeaderTooltip 3303
#define IDS_VisualProfilerCpuUsageTreeGrid_TotalSamplesHeader 3304
#define IDS_VisualProfilerCpuUsageTreeGrid_TotalSamplesHeaderTooltip 3305
#define IDS_VisualProfilerCpuUsageTreeGrid_TotalSamplesPercentHeader 3306
#define IDS_VisualProfilerCpuUsageTreeGrid_TotalSamplesPercentHeaderTooltip 3307
#define IDS_VisualProfilerErrMsg_InvalidRegularExpression 3308
#define IDS_VisualProfilerLoadDataProgressMessage 3309
#define IDS_VisualProfilerMessage_SearchNoMatches 3310
#define IDS_VisualProfilerMessage_SearchStartFromTop 3311
#define IDS_VisualProfilerMultipleModuleLabel 3312
#define IDS_VisualProfilerSampleCountLabel 3313
#define IDS_VisualProfilerSamplePercentOfProcessLabel 3314
#define IDS_VisualProfilerSearchProgressMessage 3315
#define IDS_VisualProfilerSystemCodeLabel 3316
#define IDS_VisualProfilerModulePerformanceLabel 3317
#define IDS_VisualProfilerMultiModulePerfLabel 3318
#define IDS_NetworkNetworkTooltip 6001
#define IDS_NetworkNetworkStartButtonTooltip 6002
#define IDS_NetworkNetworkStopButtonTooltip 6003
#define IDS_NetworkNetworkImportButtonTooltip 6004
#define IDS_NetworkAnalyzeDataStatus 6005
#define IDS_NetworkF12StartProfilingMessage 6006
#define IDS_NetworkF12StopProfilingMessage 6007
#define IDS_NetworkClearCacheTooltip 6008
#define IDS_NetworkClearCookiesTooltip 6009
#define IDS_NetworkF12ToolTitle 6010
#define IDS_NetworkClearSessionTooltip 6011
#define IDS_NetworkRefreshServerTooltip 6012
#define IDS_NetworkHeadersTabTitle 6013
#define IDS_NetworkParametersTabTitle 6014
#define IDS_NetworkCookiesTabTitle 6015
#define IDS_NetworkBodyTabTitle 6016
#define IDS_NetworkName 6020
#define IDS_NetworkDimensions 6021
#define IDS_NetworkContentSize 6022
#define IDS_NetworkUrl 6024
#define IDS_NetworkDimensionsFormat 6025
#define IDS_NetworkClearOnNavigateTooltip 6026
#define IDS_NetworkCacheHitAnnotation 6027
#define IDS_NetworkStalledLabel 6028
#define IDS_NetworkProxyLabel 6029
#define IDS_NetworkResolvingLabel 6030
#define IDS_NetworkConnectingLabel 6031
#define IDS_NetworkSslLabel 6032
#define IDS_NetworkSendingLabel 6033
#define IDS_NetworkWaitingLabel 6034
#define IDS_NetworkDownloadingLabel 6035
#define IDS_NetworkTimingCacheHitMessage 6036
#define IDS_NetworkTimingEmbeddedResourceMessage 6037
#define IDS_NetworkTimingRedirectedCacheHitMessage 6038
#define IDS_NetworkRedirectedFromLabel 6039
#define IDS_NetworkRedirectedToLabel 6040
#define IDS_NetworkTimingsTabTitle 6041
#define IDS_NetworkResourceNoHeader 6042
#define IDS_NetworkResourceNoBody 6043
#define IDS_NetworkResourceNoCookies 6044
#define IDS_NetworkResourceNoParameters 6045
#define IDS_NetworkResourceNoTiming 6046
#define IDS_NetworkResourceNothingSelected 6047
#define IDS_NetworkMillisecondsAbbreviation 6048
#define IDS_NetworkSecondsAbbreviation 6049
#define IDS_NetworkURLHeaderTooltip 6050
#define IDS_NetworkMethodHeaderLabel 6051
#define IDS_NetworkMethodHeaderTooltip 6052
#define IDS_NetworkStatusCodeHeaderLabel 6053
#define IDS_NetworkStatusCodeHeaderSubLabel 6054
#define IDS_NetworkStatusCodeHeaderTooltip 6055
#define IDS_NetworkContentTypeHeaderTooltip 6056
#define IDS_NetworkTransferSizeHeaderLabel 6057
#define IDS_NetworkTransferSizeHeaderTooltip 6058
#define IDS_NetworkTotalTimeHeaderLabel 6059
#define IDS_NetworkInitiatorHeaderLabel 6061
#define IDS_NetworkInitiatorHeaderSubLabel 6062
#define IDS_NetworkInitiatorHeaderTooltip 6063
#define IDS_NetworkContentTypeAll 6064
#define IDS_NetworkContentTypeFilterAllTooltip 6065
#define IDS_NetworkContentTypeDocuments 6066
#define IDS_NetworkContentTypeFilterDocumentsTooltip 6067
#define IDS_NetworkContentTypeStylesheets 6068
#define IDS_NetworkContentTypeFilterStylesheetsTooltip 6069
#define IDS_NetworkContentTypeImages 6070
#define IDS_NetworkContentTypeFilterImagesTooltip 6071
#define IDS_NetworkContentTypeScripts 6072
#define IDS_NetworkContentTypeFilterScriptsTooltip 6073
#define IDS_NetworkContentTypeXHR 6074
#define IDS_NetworkContentTypeFilterXHRTooltip 6075
#define IDS_NetworkContentTypeFonts 6076
#define IDS_NetworkContentTypeFilterFontsTooltip 6077
#define IDS_NetworkContentTypeOther 6078
#define IDS_NetworkContentTypeFilterOtherTooltip 6079
#define IDS_NetworkFilterContentType 6080
#define IDS_NetworkFilterContentTypeMenuButtonTooltipText 6081
#define IDS_NetworkContentTypeTrafficFilter 6082
#define IDS_NetworkContentTypeFilterTrafficFilterTooltip 6083
#define IDS_NetworkContentTypeMedia 6084
#define IDS_NetworkContentTypeFilterMediaTooltip 6085
#define IDS_NetworkContentTypeWebSockets 6086
#define IDS_NetworkContentTypeFilterWebSocketsTooltip 6087
#define IDS_NetworkContentTypeTextTracks 6088
#define IDS_NetworkContentTypeFilterTextTracksTooltip 6089
#define IDS_NetworkInitiatorOtherLabel 6090
#define IDS_NetworkClearDomainCacheTooltip 6091
#define IDS_NetworkClearDomainCookieTooltip 6092
#define IDS_NetworkImportSessionTooltip 6093
#define IDS_NetworkExportSessionTooltip 6094
#define IDS_NetworkOpenInNewTabContextMenu 6095
#define IDS_NetworkCopyURLContextMenu 6096
#define IDS_NetworkCopyRequestHeaderContextMenu 6097
#define IDS_NetworkCopyResponseHeaderContextMenu 6098
#define IDS_NetworkCopyRequestPayloadContextMenu 6099
#define IDS_NetworkCopyResponsePayloadContextMenu 6100
#define IDS_NetworkReplayXHRContextMenu 6101
#define IDS_NetworkCopyAsCurlContextMenu 6102
#define IDS_NetworkCopyAsPowerShellContextMenu 6103
#define IDS_NetworkCopyAsHarContextMenu 6104
#define IDS_NetworkSummaryBarRequestLabel 6105
#define IDS_NetworkSummaryBarRequestsLabel 6106
#define IDS_NetworkSummaryBarErrorLabel 6107
#define IDS_NetworkSummaryBarErrorsLabel 6108
#define IDS_NetworkStalledTooltip 6109
#define IDS_NetworkProxyTooltip 6110
#define IDS_NetworkResolvingTooltip 6111
#define IDS_NetworkConnectingTooltip 6112
#define IDS_NetworkSSLTooltip 6113
#define IDS_NetworkSendingTooltip 6114
#define IDS_NetworkWaitingTooltip 6115
#define IDS_NetworkDownloadingTooltip 6116
#define IDS_NetworkWaterfallEventMarkerTooltip 6117
#define IDS_NetworkWaterfallEventMarkerWithTimeTooltip 6118
#define IDS_NetworkInitiatorParserLabel 6119
#define IDS_NetworkInitiatorRedirectLabel 6120
#define IDS_NetworkInitiatorScriptLabel 6121
#define IDS_NetworkInitiatorHeadersLabel 6122
#define IDS_NetworkInitiatorPayloadLabel 6123
#define IDS_NetworkQueryStringParamsLabel 6124
#define IDS_NetworkInitiatorCookiesLabel 6125
#define IDS_NetworkInitiatorTimingsLabel 6126
#define IDS_NetworkCantAccessRequest 6127
#define IDS_NetworkTimelineOfEvents 6128
#define IDS_NetworkResponseLoadTimeTooltip 6129
#define IDS_NetworkReceivedLabel 6130
#define IDS_NetworkPathLabel 6132
#define IDS_NetworkRequestNameURLTooltip 6133
#define IDS_NetworkStartProfilingTooltip 6144
#define IDS_NetworkStopProfilingTooltip 6145
#define IDS_NetworkOpenSessionFailedMessage 6146
#define IDS_NetworkSaveSessionFailedMessage 6147
#define IDS_NetworkPendingLabel 6149
#define IDS_NetworkOutOfLabel 6150
#define IDS_NetworkTransferredLabel 6151
#define IDS_NetworkTakenLabel 6152
#define IDS_NetworkRequestLabel 6153
#define IDS_NetworkRequestsLabel 6154
#define IDS_NetworkErrorLabel 6155
#define IDS_NetworkErrorsLabel 6156
#define IDS_NetworkResponseBodyLabel 6157
#define IDS_NetworkRequestBodyLabel 6158
#define IDS_NetworkWordWrapButton 6159
#define IDS_NetworkPrettyPrintButtonTooltip 6160
#define IDS_NetworkContentType 6161
#define IDS_NetworkProtocolLabel 6162
#define IDS_NetworkProtocolTypeTooltip 6163
#define IDS_NetworkExportHAR 6164
#define IDS_NetworkExportHARTooltip 6165
#define IDS_NetworkResourceNoResponsePayload 6166
#define IDS_NetworkResourceNoRequestPayload 6167
#define IDS_NetworkDOMContentLoadedStats 6168
#define IDS_NetworkCopyTooltip 6169
#define IDS_NetworkCopyValue 6170
#define IDS_NetworkRequestCookies 6171
#define IDS_NetworkResponseCookies 6172
#define IDS_NetworkTotalSizeOfDeliveredResponse 6173
#define IDS_NetworkResponseStartTime 6174
#define IDS_NetworkNetworkCollectionAgentFailedToStart 6175
#define IDS_NetworkRulerLifecycleMarkLabel 6176
#define IDS_NetworkRulerUserMarkLabel 6177
#define IDS_NetworkRulerRequestHeaders 6178
#define IDS_NetworkRulerResponseHeaders 6179
#define IDS_NetworkRulerRequestURL 6180
#define IDS_NetworkRulerRequestMethod 6181
#define IDS_NetworkRulerStatusCode 6182
#define IDS_Commonvs_editor_contrib_quickOpen_gotoLine_gotoLineLabelEmptyWithLineAndColumnLimit 8048
#define IDS_Commonvs_editor_contrib_quickOpen_gotoLine_gotoLineLabelEmptyWithLineLimit 8049
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_contribution_label 8051
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_call 8052
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline__constructor 8053
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_variable2 8054
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_variable 8055
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_property 8056
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_function 8057
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_method 8058
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_interface 8059
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_class 8060
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_modules 8061
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_symbols 8062
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_QuickOutlineAction_label 8063
#define IDS_Commonvs_editor_core_view_viewImpl_editorViewAccessibleLabel 8094
#define IDS_Commonvs_editor_contrib_quickOpen_gotoLine_gotoLineActionInput 8149
#define IDS_Commonvs_editor_contrib_quickOpen_quickOutline_quickOutlineActionInput 8150
#define IDS_Commonvs_editor_contrib_quickOpen_gotoLine_gotoLineLabelValidLine 8151
#define IDS_Commonvs_editor_contrib_quickOpen_gotoLine_gotoLineLabelValidLineAndColumn 8152
#define IDS_DiagHubResourcesRulerMarkTooltipLabel 9001
#define IDS_DiagHubResourcesRulerAriaLabel 9002
#define IDS_DiagHubResourcesRulerLeftSliderAriaLabel 9003
#define IDS_DiagHubResourcesRulerRightSliderAriaLabel 9004
#define IDS_DiagHubResourcesRulerSliderAriaValueText 9005
#define IDS_DiagHubResourcesRulerLifecycleMarkLabel 9006
#define IDS_DiagHubResourcesRulerUserMarkLabel 9007
#define IDS_DiagHubResourcesUserMarkTooltip 9008
#define IDS_DiagHubResourcesRulerMarkLabel 9009
#define IDS_DiagHubResourcesRulerTitle 9010
#define IDS_DiagHubResourcesMillisecondsLabel 9011
#define IDS_DiagHubResourcesMinutesLabel 9012
#define IDS_DiagHubResourcesSecondsLabel 9013
#define IDS_DiagHubResourcesMillisecondsSelectedLabel 9014
#define IDS_DiagHubResourcesSecondsSelectedLabel 9015
#define IDS_DiagHubResourcesMinutesSelectedLabel 9016
#define IDS_DiagHubResourcesMinutesAbbreviation 9017
#define IDS_DiagHubResourcesMillisecondsAbbreviation 9018
#define IDS_DiagHubResourcesSecondsAbbreviation 9019
#define IDS_DiagHubResourcesSwimlaneCollapseAriaLabel 9020
#define IDS_DiagHubResourcesSwimlaneExpandAriaLabel 9021
#define IDS_DiagHubResourcesToolbarZoomInButton 9022
#define IDS_DiagHubResourcesToolbarClearSelectionAriaLabel 9023
#define IDS_DiagHubResourcesToolbarClearSelectionButton 9024
#define IDS_DiagHubResourcesToolbarResetViewAriaLabel 9025
#define IDS_DiagHubResourcesToolbarResetViewButton 9026
#define IDS_DiagHubResourcesToolbarZoomInAriaLabel 9027
#define IDS_DiagHubResourcesToolbarResetZoomAriaLabel 9028
#define IDS_DiagHubResourcesToolbarResetZoomButton 9029
#define IDS_DiagHubResourcesTooltipTimeLabel 9030
#define IDS_DiagHubResourcesTooltipValueLabel 9031
#define IDS_DiagHubResourcesToolbarStopCollectionButton 9032
#define IDS_DiagHubResourcesToolbarStopCollectionAriaLabel 9033
#define IDS_DiagHubResourcesToolbarStopCollectionTooltip 9034
#define IDS_DiagHubResourcesRulerAggregatedMarks 9035
#define IDS_DiagHubResourcesLifecycleMarkTooltip 9036
#define IDS_DiagHubResourcesMergedMarkTooltip 9037
#define IDS_DiagHubResourcesRulerMarkNavigation 9038
#define IDS_DiagHubResourcesperformanceDebugger_buttonApply 9039
#define IDS_DiagHubResourcesperformanceDebugger_buttonCancel 9040
#define IDS_DiagHubResourcesToolSelectionDropDownHeaderText 9041
#define IDS_DiagHubResourcesChartSeriesFormattableTooltipLabel 9042
#define IDS_DiagHubResourcesToolbarZoomToSelectionButton 9043
#define IDS_DiagHubResourcesToolbarZoomOutButton 9044
#define IDS_DiagHubResourcesToolbarZoomToSelectionAriaLabel 9045
#define IDS_DiagHubResourcesToolbarZoomOutAriaLabel 9046
#define IDS_DiagHubResourcesPerformanceDebuggerNostringMessage 9047
#define IDS_DiagHubResourcesPerformanceDebuggerNoSessionMessage 9048
#define IDS_DiagHubResourcesPerformanceSessionTerminatedMessage 9049
#define IDS_DiagHubResourcesUnsupportedBrowser 9050
#define IDS_DiagHubResourcesUnsupportedBrowserLabel 9051
#define IDS_DiagHubResourcesDocumentStatusView_Processingstring 9052
#define IDS_DiagHubResourcesInformationClose 9053
#define IDS_DiagHubResourcesInformationDroppedEvents 9054
#define IDS_DiagHubResourcesInformationLink 9055
#define IDS_DiagHubResourcesInformationPerfDebuggerSingleTarget 9056
#define IDS_DiagHubResourcesInformationProcessNameNumberSelected 9059
#define IDS_DiagHubResourcesInformationProcessNameNumber 9060
#define IDS_DiagHubResourcesInformationProcessName 9061
#define IDS_DiagHubResourcesDiagSessionTitleName 9072
#define IDS_DiagHubResourcesDiagSessionTime 9073
#define IDS_DiagHubResourcesNearestData 9074
#define IDS_DiagHubToolChangeNotice 9075
#define IDS_DiagHubConfigureToolSettings 9076
#define IDS_DiagHubSettings 9077
#define IDS_CommonExperiments 10016
#define IDS_CommonMultipleExperiments 10017
#define IDS_CommonEditCSS 10018
#define IDS_CommonEditCookies 10019
#define IDS_CommonEditWebStorage 10020
#define IDS_CommonRestartBrowserToApplySettings 10021
#define IDS_CommonEditJavaScript 10022
#define IDS_CommonSuccessfullyCompiledAsmJs 11008
#define IDS_CommonDocumentHasBeenModified 11009
#define IDS_CommonCompareDocumentsToOriginalVersions 11010
#define IDS_CommonExportChangesToDiffFile 11011
#define IDS_CommonExportAllChangesToDiffFile 11012
#define IDS_CommonSaveChangesToFile 11013
#define IDS_CommonSaveChangesAndRedirectFutureRequests 11014
#define IDS_CommonRedirectFutureURLRequests 11015
#define IDS_CommonTurnOffURLRedirection 11016
#define IDS_CommonCompareSingleDocToItsOrigin 11017
#define IDS_CommonViewOnlyOpenDoc 11018
