void AccessCheck(void){}
void AccessCheckAndAuditAlarmW(void){}
void AccessCheckByType(void){}
void AccessCheckByTypeAndAuditAlarmW(void){}
void AccessCheckByTypeResultList(void){}
void AccessCheckByTypeResultListAndAuditAlarmByHandleW(void){}
void AccessCheckByTypeResultListAndAuditAlarmW(void){}
void AddAccessAllowedAce(void){}
void AddAccessAllowedAceEx(void){}
void AddAccessAllowedObjectAce(void){}
void AddAccessDeniedAce(void){}
void AddAccessDeniedAceEx(void){}
void AddAccessDeniedObjectAce(void){}
void AddAce(void){}
void AddAuditAccessAce(void){}
void AddAuditAccessAceEx(void){}
void AddAuditAccessObjectAce(void){}
void AddMandatoryAce(void){}
void AdjustTokenGroups(void){}
void AdjustTokenPrivileges(void){}
void AllocateAndInitializeSid(void){}
void AllocateLocallyUniqueId(void){}
void AreAllAccessesGranted(void){}
void AreAnyAccessesGranted(void){}
void CheckTokenMembership(void){}
void ConvertToAutoInheritPrivateObjectSecurity(void){}
void CopySid(void){}
void CreatePrivateObjectSecurity(void){}
void CreatePrivateObjectSecurityEx(void){}
void CreatePrivateObjectSecurityWithMultipleInheritance(void){}
void CreateProcessAsUserW(void){}
void CreateRestrictedToken(void){}
void CreateWellKnownSid(void){}
void DeleteAce(void){}
void DestroyPrivateObjectSecurity(void){}
void DuplicateToken(void){}
void DuplicateTokenEx(void){}
void EqualDomainSid(void){}
void EqualPrefixSid(void){}
void EqualSid(void){}
void EventActivityIdControl(void){}
void EventEnabled(void){}
void EventProviderEnabled(void){}
void EventRegister(void){}
void EventUnregister(void){}
void EventWrite(void){}
void EventWriteEx(void){}
void EventWriteString(void){}
void EventWriteTransfer(void){}
void FindFirstFreeAce(void){}
void FreeSid(void){}
void GetAce(void){}
void GetAclInformation(void){}
void GetFileSecurityW(void){}
void GetKernelObjectSecurity(void){}
void GetLengthSid(void){}
void GetPrivateObjectSecurity(void){}
void GetSecurityDescriptorControl(void){}
void GetSecurityDescriptorDacl(void){}
void GetSecurityDescriptorGroup(void){}
void GetSecurityDescriptorLength(void){}
void GetSecurityDescriptorOwner(void){}
void GetSecurityDescriptorRMControl(void){}
void GetSecurityDescriptorSacl(void){}
void GetSidIdentifierAuthority(void){}
void GetSidLengthRequired(void){}
void GetSidSubAuthority(void){}
void GetSidSubAuthorityCount(void){}
void GetTokenInformation(void){}
void GetTraceEnableFlags(void){}
void GetTraceEnableLevel(void){}
void GetTraceLoggerHandle(void){}
void GetWindowsAccountDomainSid(void){}
void ImpersonateAnonymousToken(void){}
void ImpersonateLoggedOnUser(void){}
void ImpersonateSelf(void){}
void InitializeAcl(void){}
void InitializeSecurityDescriptor(void){}
void InitializeSid(void){}
void IsTokenRestricted(void){}
void IsValidAcl(void){}
void IsValidRelativeSecurityDescriptor(void){}
void IsValidSecurityDescriptor(void){}
void IsValidSid(void){}
void IsWellKnownSid(void){}
void MakeAbsoluteSD(void){}
void MakeSelfRelativeSD(void){}
void MapGenericMask(void){}
void ObjectCloseAuditAlarmW(void){}
void ObjectDeleteAuditAlarmW(void){}
void ObjectOpenAuditAlarmW(void){}
void ObjectPrivilegeAuditAlarmW(void){}
void OpenProcessToken(void){}
void OpenThreadToken(void){}
void PrivilegeCheck(void){}
void PrivilegedServiceAuditAlarmW(void){}
void QuerySecurityAccessMask(void){}
void RegCloseKey(void){}
void RegCopyTreeW(void){}
void RegCreateKeyExA(void){}
void RegCreateKeyExW(void){}
void RegDeleteKeyExA(void){}
void RegDeleteKeyExW(void){}
void RegDeleteTreeA(void){}
void RegDeleteTreeW(void){}
void RegDeleteValueA(void){}
void RegDeleteValueW(void){}
void RegDisablePredefinedCacheEx(void){}
void RegEnumKeyExA(void){}
void RegEnumKeyExW(void){}
void RegEnumValueA(void){}
void RegEnumValueW(void){}
void RegFlushKey(void){}
void RegGetKeySecurity(void){}
void RegGetValueA(void){}
void RegGetValueW(void){}
void RegLoadAppKeyA(void){}
void RegLoadAppKeyW(void){}
void RegLoadKeyA(void){}
void RegLoadKeyW(void){}
void RegLoadMUIStringA(void){}
void RegLoadMUIStringW(void){}
void RegNotifyChangeKeyValue(void){}
void RegOpenCurrentUser(void){}
void RegOpenKeyExA(void){}
void RegOpenKeyExW(void){}
void RegOpenUserClassesRoot(void){}
void RegQueryInfoKeyA(void){}
void RegQueryInfoKeyW(void){}
void RegQueryValueExA(void){}
void RegQueryValueExW(void){}
void RegRestoreKeyA(void){}
void RegRestoreKeyW(void){}
void RegSaveKeyExA(void){}
void RegSaveKeyExW(void){}
void RegSetKeySecurity(void){}
void RegSetValueExA(void){}
void RegSetValueExW(void){}
void RegUnLoadKeyA(void){}
void RegUnLoadKeyW(void){}
void RegisterTraceGuidsW(void){}
void RevertToSelf(void){}
void SetAclInformation(void){}
void SetFileSecurityW(void){}
void SetKernelObjectSecurity(void){}
void SetPrivateObjectSecurity(void){}
void SetPrivateObjectSecurityEx(void){}
void SetSecurityAccessMask(void){}
void SetSecurityDescriptorControl(void){}
void SetSecurityDescriptorDacl(void){}
void SetSecurityDescriptorGroup(void){}
void SetSecurityDescriptorOwner(void){}
void SetSecurityDescriptorRMControl(void){}
void SetSecurityDescriptorSacl(void){}
void SetThreadToken(void){}
void SetTokenInformation(void){}
void TraceEvent(void){}
void TraceMessageVa(void){}
void UnregisterTraceGuids(void){}
