void CallbackMayRunLong(void){}
void CancelThreadpoolIo(void){}
void CloseThreadpool(void){}
void CloseThreadpoolCleanupGroup(void){}
void CloseThreadpoolCleanupGroupMembers(void){}
void CloseThreadpoolIo(void){}
void CloseThreadpoolTimer(void){}
void CloseThreadpoolWait(void){}
void CloseThreadpoolWork(void){}
void CreateThreadpool(void){}
void CreateThreadpoolCleanupGroup(void){}
void CreateThreadpoolIo(void){}
void CreateThreadpoolTimer(void){}
void CreateThreadpoolWait(void){}
void CreateThreadpoolWork(void){}
void DisassociateCurrentThreadFromCallback(void){}
void FreeLibraryWhenCallbackReturns(void){}
void IsThreadpoolTimerSet(void){}
void LeaveCriticalSectionWhenCallbackReturns(void){}
void QueryThreadpoolStackInformation(void){}
void ReleaseMutexWhenCallbackReturns(void){}
void ReleaseSemaphoreWhenCallbackReturns(void){}
void SetEventWhenCallbackReturns(void){}
void SetThreadpoolStackInformation(void){}
void SetThreadpoolThreadMaximum(void){}
void SetThreadpoolThreadMinimum(void){}
void SetThreadpoolTimer(void){}
void SetThreadpoolTimerEx(void){}
void SetThreadpoolWait(void){}
void SetThreadpoolWaitEx(void){}
void StartThreadpoolIo(void){}
void SubmitThreadpoolWork(void){}
void TrySubmitThreadpoolCallback(void){}
void WaitForThreadpoolIoCallbacks(void){}
void WaitForThreadpoolTimerCallbacks(void){}
void WaitForThreadpoolWaitCallbacks(void){}
void WaitForThreadpoolWorkCallbacks(void){}
