void AccessCheck(void){}
void AccessCheckAndAuditAlarmW(void){}
void AccessCheckByType(void){}
void AccessCheckByTypeAndAuditAlarmW(void){}
void AccessCheckByTypeResultList(void){}
void AccessCheckByTypeResultListAndAuditAlarmByHandleW(void){}
void AccessCheckByTypeResultListAndAuditAlarmW(void){}
void AddAccessAllowedAce(void){}
void AddAccessAllowedAceEx(void){}
void AddAccessAllowedObjectAce(void){}
void AddAccessDeniedAce(void){}
void AddAccessDeniedAceEx(void){}
void AddAccessDeniedObjectAce(void){}
void AddAce(void){}
void AddAuditAccessAce(void){}
void AddAuditAccessAceEx(void){}
void AddAuditAccessObjectAce(void){}
void AddMandatoryAce(void){}
void AdjustTokenGroups(void){}
void AdjustTokenPrivileges(void){}
void AllocateAndInitializeSid(void){}
void AllocateLocallyUniqueId(void){}
void AreAllAccessesGranted(void){}
void AreAnyAccessesGranted(void){}
void CheckTokenMembership(void){}
void ConvertToAutoInheritPrivateObjectSecurity(void){}
void CopySid(void){}
void CreatePrivateObjectSecurity(void){}
void CreatePrivateObjectSecurityEx(void){}
void CreatePrivateObjectSecurityWithMultipleInheritance(void){}
void CreateRestrictedToken(void){}
void CreateWellKnownSid(void){}
void DeleteAce(void){}
void DestroyPrivateObjectSecurity(void){}
void DuplicateToken(void){}
void DuplicateTokenEx(void){}
void EqualDomainSid(void){}
void EqualPrefixSid(void){}
void EqualSid(void){}
void FindFirstFreeAce(void){}
void FreeSid(void){}
void GetAce(void){}
void GetAclInformation(void){}
void GetFileSecurityW(void){}
void GetKernelObjectSecurity(void){}
void GetLengthSid(void){}
void GetPrivateObjectSecurity(void){}
void GetSecurityDescriptorControl(void){}
void GetSecurityDescriptorDacl(void){}
void GetSecurityDescriptorGroup(void){}
void GetSecurityDescriptorLength(void){}
void GetSecurityDescriptorOwner(void){}
void GetSecurityDescriptorRMControl(void){}
void GetSecurityDescriptorSacl(void){}
void GetSidIdentifierAuthority(void){}
void GetSidLengthRequired(void){}
void GetSidSubAuthority(void){}
void GetSidSubAuthorityCount(void){}
void GetTokenInformation(void){}
void GetWindowsAccountDomainSid(void){}
void ImpersonateAnonymousToken(void){}
void ImpersonateLoggedOnUser(void){}
void ImpersonateSelf(void){}
void InitializeAcl(void){}
void InitializeSecurityDescriptor(void){}
void InitializeSid(void){}
void IsTokenRestricted(void){}
void IsValidAcl(void){}
void IsValidRelativeSecurityDescriptor(void){}
void IsValidSecurityDescriptor(void){}
void IsValidSid(void){}
void IsWellKnownSid(void){}
void MakeAbsoluteSD(void){}
void MakeAbsoluteSD2(void){}
void MakeSelfRelativeSD(void){}
void MapGenericMask(void){}
void ObjectCloseAuditAlarmW(void){}
void ObjectDeleteAuditAlarmW(void){}
void ObjectOpenAuditAlarmW(void){}
void ObjectPrivilegeAuditAlarmW(void){}
void PrivilegeCheck(void){}
void PrivilegedServiceAuditAlarmW(void){}
void QuerySecurityAccessMask(void){}
void RevertToSelf(void){}
void SetAclInformation(void){}
void SetFileSecurityW(void){}
void SetKernelObjectSecurity(void){}
void SetPrivateObjectSecurity(void){}
void SetPrivateObjectSecurityEx(void){}
void SetSecurityAccessMask(void){}
void SetSecurityDescriptorControl(void){}
void SetSecurityDescriptorDacl(void){}
void SetSecurityDescriptorGroup(void){}
void SetSecurityDescriptorOwner(void){}
void SetSecurityDescriptorRMControl(void){}
void SetSecurityDescriptorSacl(void){}
void SetTokenInformation(void){}
