/*
 * capabilities.c
 *
 * Generates a random alphanumeric string for the computer name.
 */
#pragma warning (disable:4005)

#include <windows.h>
#include <winternl.h>
#include <ntstatus.h>
#include <stdlib.h>

#pragma comment(lib, "ntdll.lib")

NTSYSAPI ULONG NTAPI RtlRandomEx(PULONG Seed);

// ------------------------------------------------------------------
// GenerateRandomChars
// Fills a buffer with random characters from the set
// "0123456789ABCDEFGHIJKLMNOPQRSTUV" using a 30‑bit random number
// generated by RtlRandomEx.
// ------------------------------------------------------------------
NTSTATUS GenerateRandomChars(ULONG Seed, PWSTR Buffer, SIZE_T BufferSize)
{
    ULONG state[2];
    BYTE randomBits[24];   // 192 bits = 6 * 32‑bit
    ULONG bitPos = 0;
    ULONG charIndex = 0;
    ULONG remaining = (ULONG)BufferSize;

    state[0] = Seed;
    state[1] = 0;

    // Generate 6 random DWORDs
    for (int i = 0; i < 6; i++) {
        state[0] = RtlRandomEx(state);
        *(DWORD*)(randomBits + i * 4) = RtlRandomEx(state);
    }

    // Use only as many bits as needed for the buffer (minus null terminator)
    // Each character uses 5 bits (since 0‑31).
    // We'll consume bits from the random stream.
    while (charIndex < remaining - 1) {
        // Extract 5 bits from the bit stream
        ULONG bitOffset = bitPos % 8;
        ULONG byteIndex = bitPos / 8;
        if (byteIndex >= 24) {
            // Ran out of random bits; we could generate more, but the original code loops
            // using only the 6 DWORDs. The original loop runs 5 times for each char? Actually it generates only 6 DWORDs.
            // We'll just break to avoid infinite loop.
            break;
        }
        ULONG bits = 0;
        // Extract up to 5 bits starting at bitPos
        for (int i = 0; i < 5; i++) {
            ULONG bit = (randomBits[byteIndex + (bitOffset + i) / 8] >> ((bitOffset + i) % 8)) & 1;
            bits |= (bit << i);
        }
        bitPos += 5;

        if (bits < 30) {
            // Valid character
            Buffer[charIndex++] = L"0123456789ABCDEFGHIJKLMNOPQRSTUV"[bits];
        }
        // else discard and try again
    }

    Buffer[charIndex] = 0;
    return STATUS_SUCCESS;
}

