void AcquireSRWLockExclusive(void){}
void AcquireSRWLockShared(void){}
void AssignMemoryToSocDomain(void){}
void AwaitSmc(void){}
void CloseHandle(void){}
void CloseThreadpoolIo(void){}
void CloseThreadpoolTimer(void){}
void CloseThreadpoolWait(void){}
void CloseThreadpoolWork(void){}
void CreateEventW(void){}
void CreateSecureDevice(void){}
void CreateSecureSection(void){}
void CreateSecureSectionSpecifyPages(void){}
void CreateSemaphoreW(void){}
void CreateThread(void){}
void CreateThreadpoolIo(void){}
void CreateThreadpoolTimer(void){}
void CreateThreadpoolWait(void){}
void CreateThreadpoolWork(void){}
void DebugBreak(void){}
void DecryptData(void){}
void DecryptISKBoundData(void){}
void DeleteCriticalSection(void){}
void DmaMapMemory(void){}
void DuplicateHandle(void){}
void EmitSmc(void){}
void EncryptData(void){}
void EnterCriticalSection(void){}
void EventRegister(void){}
void EtwEventRegister(void){}
void EventSetInformation(void){}
void EtwEventSetInformation(void){}
void EventUnregister(void){}
void EtwEventUnregister(void){}
void EventWrite(void){}
void EtwEventWrite(void){}
void EventWriteTransfer(void){}
void EtwEventWriteTransfer(void){}
void ExitProcess(void){}
void ExitThread(void){}
void FileTimeToSystemTime(void){}
void FlushSecureSectionBuffers(void){}
void FreeLibrary(void){}
void FreeLibraryWhenCallbackReturns(void){}
void GetCommandLineW(void){}
void GetCurrentProcess(void){}
void GetCurrentProcessId(void){}
void GetCurrentThread(void){}
void GetCurrentThreadId(void){}
void GetDmaEnabler(void){}
void GetEnvironmentStringsW(void){}
void GetEnvironmentVariableW(void){}
void GetExitCodeThread(void){}
void GetExposedSecureSection(void){}
void GetFipsModeFromIumKernelState(void){}
void GetLastError(void){}
void GetLocalTime(void){}
void GetModuleHandleW(void){}
void GetProcAddress(void){}
void GetProcessHeap(void){}
void GetSecureIdentityKey(void){}
void GetSecureIdentitySigningKey(void){}
void GetSeedFromIumKernelState(void){}
void GetSignedReport(void){}
void GetStartupInfoW(void){}
void GetSystemFirmwareTable(void){}
void GetSystemInfo(void){}
void GetSystemTime(void){}
void GetSystemTimeAsFileTime(void){}
void GetTaggedData(void){}
void GetTaggedDataSize(void){}
void GetThreadId(void){}
void GetThreadPriority(void){}
void GetTickCount(void){}
void GetTickCount64(void){}
void GetTpmBindingInfo(void){}
void GetTraceEnableFlags(void){}
void EtwGetTraceEnableFlags(void){}
void GetTraceEnableLevel(void){}
void EtwGetTraceEnableLevel(void){}
void GetTraceLoggerHandle(void){}
void EtwGetTraceLoggerHandle(void){}
void HeapAlloc(void){}
void HeapCreate(void){}
void HeapDestroy(void){}
void HeapFree(void){}
void HeapLock(void){}
void HeapQueryInformation(void){}
void HeapReAlloc(void){}
void HeapSetInformation(void){}
void HeapSize(void){}
void HeapUnlock(void){}
void HeapValidate(void){}
void InitializeCriticalSection(void){}
void InitializeCriticalSectionAndSpinCount(void){}
void InitializeCriticalSectionEx(void){}
void InitializeSListHead(void){}
void InitializeSRWLock(void){}
void IsDebuggerPresent(void){}
void IsProcessorFeaturePresent(void){}
void IsSecureProcess(void){}
void LeaveCriticalSection(void){}
void LeaveCriticalSectionWhenCallbackReturns(void){}
void LoadLibraryExW(void){}
void MapSecureIo(void){}
void MapViewOfFile(void){}
void NdrClientCall3(void){}
void NdrServerCall2(void){}
void NdrServerCallAll(void){}
void NtAlertThreadByThreadId(void){}
void NtOpenProcessToken(void){}
void NtOpenThreadToken(void){}
void NtQueryInformationProcess(void){}
void NtQueryInformationThread(void){}
void NtQueryInformationToken(void){}
void NtSetInformationProcess(void){}
void NtSetInformationThread(void){}
void NtTraceControl(void){}
void NtTraceEvent(void){}
void NtWaitForAlertByThreadId(void){}
void OpenCurrentExtension(void){}
void OpenEventW(void){}
void OpenSecureSection(void){}
void OutputDebugStringW(void){}
void PostMailbox(void){}
void ProtectSecureIo(void){}
void QueryPerformanceCounter(void){}
void QueryPerformanceFrequency(void){}
void QuerySecureDeviceInformation(void){}
void QueryThreadCycleTime(void){}
void RaiseException(void){}
void RaiseFailFastException(void){}
void RegisterTraceGuidsW(void){}
void EtwRegisterTraceGuidsW(void){}
void ReleaseSRWLockExclusive(void){}
void ReleaseSRWLockShared(void){}
void ReleaseSemaphore(void){}
void ReleaseSemaphoreWhenCallbackReturns(void){}
void ResetEvent(void){}
void RpcExceptionFilter(void){}
void RpcMgmtStopServerListening(void){}
void RpcMgmtWaitServerListen(void){}
void RpcServerInqCallAttributesW(void){}
void RpcServerListen(void){}
void RpcServerRegisterIf(void){}
void RpcServerUnregisterIf(void){}
void RpcServerUseProtseqEpW(void){}
void RtlAvlInsertNodeEx(void){}
void RtlAvlRemoveNode(void){}
void RtlCaptureContext(void){}
void RtlEqualUnicodeString(void){}
void RtlGUIDFromString(void){}
void RtlImageNtHeader(void){}
void RtlInitUnicodeString(void){}
void RtlInterlockedPushListSList(void){}
void RtlLookupFunctionEntry(void){}
void RtlNtStatusToDosError(void){}
void RtlRandom(void){}
void RtlRandomEx(void){}
void RtlTimeToTimeFields(void){}
void RtlVirtualUnwind(void){}
void SecureStorageGet(void){}
void SecureStoragePut(void){}
void SetDmaTargetProperties(void){}
void SetEnvironmentVariableW(void){}
void SetEvent(void){}
void SetEventWhenCallbackReturns(void){}
void SetLastError(void){}
void SetPolicyExtension(void){}
void SetThreadpoolTimer(void){}
void SetThreadpoolTimerEx(void){}
void SetThreadpoolWait(void){}
void SetUnhandledExceptionFilter(void){}
void Sleep(void){}
void StartThreadpoolIo(void){}
void SystemTimeToFileTime(void){}
void TerminateProcess(void){}
void TerminateThread(void){}
void TlsAlloc(void){}
void TlsFree(void){}
void TlsGetValue(void){}
void TlsSetValue(void){}
void TraceMessage(void){}
void EtwTraceMessage(void){}
void TraceMessageVa(void){}
void EtwTraceMessageVa(void){}
void TryAcquireSRWLockExclusive(void){}
void TryAcquireSRWLockShared(void){}
void UnhandledExceptionFilter(void){}
void UnmapSecureIo(void){}
void UnmapViewOfFile(void){}
void UnregisterTraceGuids(void){}
void EtwUnregisterTraceGuids(void){}
void UpdateSecureDeviceState(void){}
void UuidCreate(void){}
void VbsVmSysCall(void){}
void VerifyEnclaveAttestationReport(void){}
void VirtualAlloc(void){}
void VirtualFree(void){}
void VirtualProtect(void){}
void VirtualQuery(void){}
void WaitForMultipleObjects(void){}
void WaitForSingleObject(void){}
void WaitForSingleObjectEx(void){}
void WaitForThreadpoolIoCallbacks(void){}
void WaitForThreadpoolTimerCallbacks(void){}
void WaitForThreadpoolWaitCallbacks(void){}
void WaitForThreadpoolWorkCallbacks(void){}
void WideCharToMultiByte(void){}
void vDbgPrintEx(void){}
void vDbgPrintExWithPrefix(void){}
