#include <rpc.h>
#include <rpcndr.h>

// Forward declarations for MIDL-generated types
typedef struct _NSI_MODULE_DESC {
    void *ModuleId;
    ULONG ObjectIndex;
    DWORD NsiModule;
} NSI_MODULE_DESC;

typedef struct _NSI_KEYSTRUCT_DESC {
    UCHAR *KeyStruct;
    ULONG KeyStructLength;
} NSI_KEYSTRUCT_DESC;

typedef struct _NSI_SINGLE_PARAM_DESC {
    DWORD StructType;
    UCHAR *Parameter;
    ULONG ParameterLength;
    ULONG ParameterOffset;
} NSI_SINGLE_PARAM_DESC;

typedef struct _NSI_PARAM_STRUCT_DESC {
    UCHAR *RwParameterStruct;
    ULONG RwParameterStructLength;
    UCHAR *RoDynamicParameterStruct;
    ULONG RoDynamicParameterStructLength;
    UCHAR *RoStaticParameterStruct;
    ULONG RoStaticParameterStructLength;
} NSI_PARAM_STRUCT_DESC;

typedef struct _NSI_KEYSTRUCT_DESC_ENUM {
    UCHAR *KeyStruct;
    ULONG KeyStructLength;
    ULONG TotalKeyStructLength;
} NSI_KEYSTRUCT_DESC_ENUM;

typedef struct _NSI_PARAM_STRUCT_DESC_ENUM {
    UCHAR *RwParameterStruct;
    ULONG RwParameterStructLength;
    ULONG TotalRwLength;
    UCHAR *RoStaticParameterStruct;
    ULONG RoStaticParameterStructLength;
    ULONG TotalRoStaticLength;
    UCHAR *RoDynamicParameterStruct;
    ULONG RoDynamicParameterStructLength;
    ULONG TotalRoDynamicLength;
} NSI_PARAM_STRUCT_DESC_ENUM;

typedef struct _NSI_RW_PARAM_STRUCT_DESC {
    UCHAR *RwParameterStruct;
    ULONG RwParameterStructLength;
} NSI_RW_PARAM_STRUCT_DESC;

typedef struct _NSI_NOTIFICATION_REGISTRATION_DESC {
    ULONG CompartmentScope;
    ULONG CompartmentId;
} NSI_NOTIFICATION_REGISTRATION_DESC;

typedef struct _NSI_NOTIFICATION {
    HANDLE EventHandle;
} NSI_NOTIFICATION;

// Constants
typedef DWORD NSI_STORE;
typedef DWORD NSI_GET_ACTION;
typedef DWORD NSI_SET_ACTION;
typedef DWORD NSI_STRUCT_TYPE;

// Format string and type format string data (these would normally be generated by MIDL)
static unsigned char WINNSI_FormatString[] = { 0 };
static unsigned char WINNSI_TypeFormatString[] = { 0 };

// WINNSI_StubDesc definition
MIDL_STUB_DESC WINNSI_StubDesc = {
    NULL,                               // RpcInterfaceInformation
    NULL,                               // pfnAllocate
    NULL,                               // pfnFree
    NULL,                               // IMPLEMENTATION_OR_PIPE_HANDLE
    0,                                  // Version
    (const GENERIC_BINDING_ROUTINE_PAIR *)WINNSI_TypeFormatString,            // pFormatTypes
    (const EXPR_EVAL *)WINNSI_FormatString,                // pFormatString
    (const XMIT_ROUTINE_QUINTUPLE *)WINNSI_TypeFormatString,            // pTypeFormatString
    NULL,                               // aUserMarshalQuadruple
    1,                                  // fCheckBounds
    1,                                  // fBufferCheck
    0,                                  // fInDontFree
    0,                                  // fDontCallFreeInst
    0,                                  // fUnused
    0,                                  // fHasExtensions
    0,                                  // fHasNewCorrDesc
    0,                                  // ClientCorrCheck
    0,                                  // ServerCorrCheck
    0,                                  // NotifyRefCount
    NULL,                               // pMallocFreeStruct
};

void __cdecl RpcNsiDeregisterChangeNotification(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    void **notificationHandle
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x1000132C, asyncState);
}

void __cdecl RpcNsiEnumerateObjectsAllParameters(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    NSI_STORE store,
    NSI_GET_ACTION action,
    NSI_KEYSTRUCT_DESC_ENUM *keyStructDesc,
    NSI_PARAM_STRUCT_DESC_ENUM *paramStructDesc,
    ULONG *entryCount
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x10001232, asyncState);
}

void __cdecl RpcNsiGetAllParameters(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    NSI_STORE store,
    NSI_GET_ACTION action,
    NSI_KEYSTRUCT_DESC *keyStructDesc,
    NSI_PARAM_STRUCT_DESC *paramStructDesc
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x100011F2, asyncState);
}

void __cdecl RpcNsiGetParameter(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    NSI_STORE store,
    NSI_GET_ACTION action,
    NSI_KEYSTRUCT_DESC *keyStructDesc,
    NSI_SINGLE_PARAM_DESC *paramDesc
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x100011B2, asyncState);
}

void __cdecl RpcNsiRegisterChangeNotification(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    NSI_NOTIFICATION_REGISTRATION_DESC registrationDesc,
    void **notificationHandle
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x100012F8, asyncState);
}

void __cdecl RpcNsiRequestChangeNotification(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    void *notificationHandle,
    NSI_KEYSTRUCT_DESC *keyStructDesc,
    NSI_SINGLE_PARAM_DESC *paramDesc,
    NSI_NOTIFICATION *notification
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x1000135A, asyncState);
}

void __cdecl RpcNsiSetAllParameters(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    NSI_STORE store,
    NSI_SET_ACTION action,
    NSI_KEYSTRUCT_DESC *keyStructDesc,
    NSI_RW_PARAM_STRUCT_DESC *paramStructDesc
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x100012B8, asyncState);
}

void __cdecl RpcNsiSetParameter(
    PRPC_ASYNC_STATE asyncState,
    void *context,
    NSI_MODULE_DESC moduleDesc,
    NSI_STORE store,
    NSI_SET_ACTION action,
    NSI_KEYSTRUCT_DESC *keyStructDesc,
    NSI_SINGLE_PARAM_DESC *paramDesc
)
{
    NdrAsyncClientCall(&WINNSI_StubDesc, (PFORMAT_STRING)0x10001278, asyncState);
}

