void AddAtomA(void){}
void AddAtomW(void){}
void BackupRead(void){}
void BackupWrite(void){}
void BindIoCompletionCallback(void){}
void ConvertFiberToThread(void){}
void ConvertThreadToFiber(void){}
void CopyFileA(void){}
void CopyFileW(void){}
void CreateFiber(void){}
void CreateFileMappingA(void){}
void CreateFileTransactedW(void){}
void CreateMailslotA(void){}
void CreateNamedPipeA(void){}
void CreateSemaphoreW(void){}
void DeleteAtom(void){}
void DeleteFiber(void){}
void DnsHostnameToComputerNameW(void){}
void DosDateTimeToFileTime(void){}
void FatalAppExitA(void){}
void FatalAppExitW(void){}
void FileTimeToDosDateTime(void){}
void FindAtomA(void){}
void FindAtomW(void){}
void FindResourceA(void){}
void FindResourceExA(void){}
void FindResourceW(void){}
void GetActiveProcessorCount(void){}
void GetAtomNameA(void){}
void GetAtomNameW(void){}
void GetComputerNameA(void){}
void GetComputerNameW(void){}
void GetConsoleWindow(void){}
void GetDurationFormatEx(void){}
void GetFirmwareEnvironmentVariableW(void){}
void GetMaximumProcessorGroupCount(void){}
void GetNamedPipeClientProcessId(void){}
void GetNamedPipeServerProcessId(void){}
void GetPrivateProfileIntA(void){}
void GetPrivateProfileIntW(void){}
void GetPrivateProfileSectionW(void){}
void GetPrivateProfileStringA(void){}
void GetPrivateProfileStringW(void){}
void GetProcessAffinityMask(void){}
void GetProcessIoCounters(void){}
void GetProfileIntA(void){}
void GetProfileIntW(void){}
void GetProfileSectionA(void){}
void GetProfileSectionW(void){}
void GetProfileStringA(void){}
void GetProfileStringW(void){}
void GetShortPathNameA(void){}
void GetStartupInfoA(void){}
void GetStringTypeExA(void){}
void GetSystemPowerStatus(void){}
void GetSystemWow64DirectoryA(void){}
void GetSystemWow64DirectoryW(void){}
void GetTapeParameters(void){}
void GetTempPathA(void){}
void GetThreadSelectorEntry(void){}
void GlobalAddAtomA(void){}
void GlobalAddAtomW(void){}
void GlobalAlloc(void){}
void GlobalDeleteAtom(void){}
void GlobalFindAtomA(void){}
void GlobalFindAtomW(void){}
void GlobalFlags(void){}
void GlobalFree(void){}
void GlobalGetAtomNameA(void){}
void GlobalGetAtomNameW(void){}
void GlobalHandle(void){}
void GlobalLock(void){}
void GlobalMemoryStatus(void){}
void GlobalReAlloc(void){}
void GlobalSize(void){}
void GlobalUnlock(void){}
void InitAtomTable(void){}
void LoadLibraryA(void){}
void LoadLibraryW(void){}
void LocalAlloc(void){}
void LocalFlags(void){}
void LocalFree(void){}
void LocalLock(void){}
void LocalReAlloc(void){}
void LocalSize(void){}
void LocalUnlock(void){}
void MoveFileA(void){}
void MoveFileExA(void){}
void MoveFileW(void){}
void MulDiv(void){}
void OpenFile(void){}
void PulseEvent(void){}
void RaiseFailFastException(void){}
void RegisterWaitForSingleObject(void){}
void SetConsoleTitleA(void){}
void SetFileCompletionNotificationModes(void){}
void SetFirmwareEnvironmentVariableW(void){}
void SetHandleCount(void){}
void SetMailslotInfo(void){}
void SetProcessAffinityMask(void){}
void SetThreadAffinityMask(void){}
void SetThreadIdealProcessor(void){}
void SetVolumeLabelW(void){}
void SwitchToFiber(void){}
void UnregisterWait(void){}
void WTSGetActiveConsoleSessionId(void){}
void WaitForMultipleObjects(void){}
void WritePrivateProfileSectionA(void){}
void WritePrivateProfileSectionW(void){}
void WritePrivateProfileStringA(void){}
void WritePrivateProfileStringW(void){}
void lstrcatW(void){}
void lstrcmpA(void){}
void lstrcmpW(void){}
void lstrcmpiA(void){}
void lstrcmpiW(void){}
void lstrcpyW(void){}
void lstrcpynA(void){}
void lstrcpynW(void){}
void lstrlenA(void){}
void lstrlenW(void){}
