void CharLowerA(void){}
void CharLowerBuffA(void){}
void CharLowerBuffW(void){}
void CharLowerW(void){}
void CharNextA(void){}
void CharNextExA(void){}
void CharNextW(void){}
void CharPrevA(void){}
void CharPrevExA(void){}
void CharPrevW(void){}
void CharUpperA(void){}
void CharUpperBuffA(void){}
void CharUpperBuffW(void){}
void CharUpperW(void){}
void IsCharAlphaA(void){}
void IsCharAlphaNumericA(void){}
void IsCharAlphaNumericW(void){}
void IsCharAlphaW(void){}
void IsCharLowerA(void){}
void IsCharLowerW(void){}
void IsCharUpperA(void){}
void IsCharUpperW(void){}
void LoadStringA(void){}
void LoadStringW(void){}
