void AddLocalAlternateComputerNameW(void){}
void BackupRead(void){}
void BackupSeek(void){}
void BackupWrite(void){}
void BindIoCompletionCallback(void){}
void CopyFileA(void){}
void CopyFileW(void){}
void CreateFileMappingA(void){}
void CreateFileTransactedW(void){}
void CreateMailslotA(void){}
void CreateNamedPipeA(void){}
void CreateSemaphoreW(void){}
void DnsHostnameToComputerNameW(void){}
void DosDateTimeToFileTime(void){}
void FatalAppExitA(void){}
void FatalAppExitW(void){}
void FileTimeToDosDateTime(void){}
void FindResourceA(void){}
void FindResourceExA(void){}
void FindResourceW(void){}
void GetComputerNameA(void){}
void GetComputerNameW(void){}
void GetConsoleWindow(void){}
void GetDurationFormatEx(void){}
void GetMaximumProcessorGroupCount(void){}
void GetNamedPipeClientProcessId(void){}
void GetNamedPipeServerProcessId(void){}
void GetShortPathNameA(void){}
void GetStartupInfoA(void){}
void GetStringTypeExA(void){}
void GetSystemPowerStatus(void){}
void GetSystemWow64DirectoryA(void){}
void GetSystemWow64DirectoryW(void){}
void GetTapeParameters(void){}
void GetTempPathA(void){}
void GetThreadSelectorEntry(void){}
void GlobalMemoryStatus(void){}
void IsSystemResumeAutomatic(void){}
void LoadLibraryA(void){}
void LoadLibraryW(void){}
void MoveFileA(void){}
void MoveFileExA(void){}
void MoveFileW(void){}
void MulDiv(void){}
void OpenFile(void){}
void PulseEvent(void){}
void RaiseFailFastException(void){}
void RegisterWaitForSingleObject(void){}
void RequestWakeupLatency(void){}
void SetConsoleTitleA(void){}
void SetFileCompletionNotificationModes(void){}
void SetHandleCount(void){}
void SetMailslotInfo(void){}
void SetSystemPowerState(void){}
void SetVolumeLabelW(void){}
void UnregisterWait(void){}
void WTSGetActiveConsoleSessionId(void){}
void WaitForMultipleObjects(void){}
