void RegConnectRegistryA(void){}
void RegConnectRegistryW(void){}
void RegCopyTreeA(void){}
void RegCreateKeyA(void){}
void RegCreateKeyTransactedA(void){}
void RegCreateKeyTransactedW(void){}
void RegCreateKeyW(void){}
void RegDeleteKeyA(void){}
void RegDeleteKeyTransactedA(void){}
void RegDeleteKeyTransactedW(void){}
void RegDeleteKeyValueA(void){}
void RegDeleteKeyValueW(void){}
void RegDeleteKeyW(void){}
void RegDisablePredefinedCache(void){}
void RegEnumKeyA(void){}
void RegEnumKeyW(void){}
void RegOpenKeyA(void){}
void RegOpenKeyTransactedA(void){}
void RegOpenKeyTransactedW(void){}
void RegOpenKeyW(void){}
void RegOverridePredefKey(void){}
void RegQueryMultipleValuesA(void){}
void RegQueryMultipleValuesW(void){}
void RegQueryValueA(void){}
void RegQueryValueW(void){}
void RegReplaceKeyA(void){}
void RegReplaceKeyW(void){}
void RegSaveKeyA(void){}
void RegSaveKeyW(void){}
void RegSetKeyValueA(void){}
void RegSetKeyValueW(void){}
void RegSetValueA(void){}
void RegSetValueW(void){}
