void ChangeServiceConfig2A(void){}
void ChangeServiceConfig2W(void){}
void ChangeServiceConfigA(void){}
void ChangeServiceConfigW(void){}
void CloseServiceHandle(void){}
void CloseTrace(void){}
void ControlService(void){}
void ControlServiceExA(void){}
void ControlServiceExW(void){}
void ControlTraceA(void){}
void ControlTraceW(void){}
void ConvertSecurityDescriptorToStringSecurityDescriptorW(void){}
void ConvertSidToStringSidW(void){}
void ConvertStringSecurityDescriptorToSecurityDescriptorW(void){}
void ConvertStringSidToSidW(void){}
void CreateServiceA(void){}
void CreateServiceW(void){}
void CredDeleteA(void){}
void CredDeleteW(void){}
void CredEnumerateA(void){}
void CredEnumerateW(void){}
void CredFindBestCredentialA(void){}
void CredFindBestCredentialW(void){}
void CredFree(void){}
void CredGetSessionTypes(void){}
void CredGetTargetInfoA(void){}
void CredGetTargetInfoW(void){}
void CredIsMarshaledCredentialW(void){}
void CredIsProtectedA(void){}
void CredIsProtectedW(void){}
void CredMarshalCredentialA(void){}
void CredMarshalCredentialW(void){}
void CredProtectA(void){}
void CredProtectW(void){}
void CredReadA(void){}
void CredReadDomainCredentialsA(void){}
void CredReadDomainCredentialsW(void){}
void CredReadW(void){}
void CredUnmarshalCredentialA(void){}
void CredUnmarshalCredentialW(void){}
void CredUnprotectA(void){}
void CredUnprotectW(void){}
void CredWriteA(void){}
void CredWriteDomainCredentialsA(void){}
void CredWriteDomainCredentialsW(void){}
void CredWriteW(void){}
void DeleteService(void){}
void EnableTraceEx2(void){}
void EnumDependentServicesW(void){}
void EnumServicesStatusExW(void){}
void EnumerateTraceGuidsEx(void){}
void EventAccessControl(void){}
void EventAccessQuery(void){}
void EventAccessRemove(void){}
void NotifyServiceStatusChangeA(void){}
void NotifyServiceStatusChangeW(void){}
void OpenSCManagerA(void){}
void OpenSCManagerW(void){}
void OpenServiceA(void){}
void OpenServiceW(void){}
void OpenTraceW(void){}
void ProcessTrace(void){}
void QueryAllTracesA(void){}
void QueryAllTracesW(void){}
void QueryServiceConfig2A(void){}
void QueryServiceConfig2W(void){}
void QueryServiceConfigA(void){}
void QueryServiceConfigW(void){}
void QueryServiceObjectSecurity(void){}
void QueryServiceStatus(void){}
void QueryServiceStatusEx(void){}
void RegisterServiceCtrlHandlerA(void){}
void RegisterServiceCtrlHandlerExA(void){}
void RegisterServiceCtrlHandlerExW(void){}
void RegisterServiceCtrlHandlerW(void){}
void RegisterTraceGuidsA(void){}
void RemoveTraceCallback(void){}
void SetServiceObjectSecurity(void){}
void SetServiceStatus(void){}
void SetTraceCallback(void){}
void StartServiceA(void){}
void StartServiceCtrlDispatcherA(void){}
void StartServiceCtrlDispatcherW(void){}
void StartServiceW(void){}
void StartTraceA(void){}
void StartTraceW(void){}
void StopTraceW(void){}
void TraceSetInformation(void){}
