void ChangeServiceConfig2A(void){}
void ChangeServiceConfigA(void){}
void ControlService(void){}
void ControlServiceExA(void){}
void CreateServiceA(void){}
void I_QueryTagInformation(void){}
void I_ScBroadcastServiceControlMessage(void){}
void I_ScIsSecurityProcess(void){}
void I_ScPnPGetServiceName(void){}
void I_ScQueryServiceConfig(void){}
void I_ScRpcBindA(void){}
void I_ScRpcBindW(void){}
void I_ScSendPnPMessage(void){}
void I_ScSendTSMessage(void){}
void I_ScValidatePnPService(void){}
void NotifyServiceStatusChangeA(void){}
void OpenSCManagerA(void){}
void OpenServiceA(void){}
void QueryServiceConfig2A(void){}
void QueryServiceConfigA(void){}
void QueryServiceStatus(void){}
void RegisterServiceCtrlHandlerA(void){}
void RegisterServiceCtrlHandlerExA(void){}
void RegisterServiceCtrlHandlerW(void){}
void StartServiceA(void){}
void StartServiceCtrlDispatcherA(void){}
