void IsCharBlankW(void){}
void IsCharCntrlW(void){}
void IsCharDigitW(void){}
void IsCharPunctW(void){}
void IsCharSpaceA(void){}
void IsCharSpaceW(void){}
void IsCharXDigitW(void){}
void PathAddBackslashA(void){}
void PathAddBackslashW(void){}
void PathAddExtensionA(void){}
void PathAddExtensionW(void){}
void PathAppendA(void){}
void PathAppendW(void){}
void PathCanonicalizeA(void){}
void PathCanonicalizeW(void){}
void PathCombineA(void){}
void PathCombineW(void){}
void PathCommonPrefixA(void){}
void PathCommonPrefixW(void){}
void PathFileExistsA(void){}
void PathFileExistsW(void){}
void PathFindExtensionA(void){}
void PathFindExtensionW(void){}
void PathFindFileNameA(void){}
void PathFindFileNameW(void){}
void PathFindNextComponentA(void){}
void PathFindNextComponentW(void){}
void PathGetArgsA(void){}
void PathGetArgsW(void){}
void PathGetCharTypeA(void){}
void PathGetCharTypeW(void){}
void PathGetDriveNumberA(void){}
void PathGetDriveNumberW(void){}
void PathIsFileSpecA(void){}
void PathIsFileSpecW(void){}
void PathIsLFNFileSpecA(void){}
void PathIsLFNFileSpecW(void){}
void PathIsPrefixA(void){}
void PathIsPrefixW(void){}
void PathIsRelativeA(void){}
void PathIsRelativeW(void){}
void PathIsRootA(void){}
void PathIsRootW(void){}
void PathIsSameRootA(void){}
void PathIsSameRootW(void){}
void PathIsUNCA(void){}
void PathIsUNCServerA(void){}
void PathIsUNCServerShareA(void){}
void PathIsUNCServerShareW(void){}
void PathIsUNCServerW(void){}
void PathIsUNCW(void){}
void PathIsValidCharA(void){}
void PathIsValidCharW(void){}
void PathMatchSpecA(void){}
void PathMatchSpecExA(void){}
void PathMatchSpecExW(void){}
void PathMatchSpecW(void){}
void PathParseIconLocationA(void){}
void PathParseIconLocationW(void){}
void PathQuoteSpacesA(void){}
void PathQuoteSpacesW(void){}
void PathRelativePathToA(void){}
void PathRelativePathToW(void){}
void PathRemoveBackslashA(void){}
void PathRemoveBackslashW(void){}
void PathRemoveBlanksA(void){}
void PathRemoveBlanksW(void){}
void PathRemoveExtensionA(void){}
void PathRemoveExtensionW(void){}
void PathRemoveFileSpecA(void){}
void PathRemoveFileSpecW(void){}
void PathRenameExtensionA(void){}
void PathRenameExtensionW(void){}
void PathSearchAndQualifyA(void){}
void PathSearchAndQualifyW(void){}
void PathSkipRootA(void){}
void PathSkipRootW(void){}
void PathStripPathA(void){}
void PathStripPathW(void){}
void PathStripToRootA(void){}
void PathStripToRootW(void){}
void PathUnExpandEnvStringsA(void){}
void PathUnExpandEnvStringsW(void){}
void PathUnquoteSpacesA(void){}
void PathUnquoteSpacesW(void){}
void SHExpandEnvironmentStringsA(void){}
void SHExpandEnvironmentStringsW(void){}
void SHTruncateString(void){}
