void GetComputerNameExA(void){}
void GetComputerNameExW(void){}
void GetLocalTime(void){}
void GetLogicalProcessorInformation(void){}
void GetLogicalProcessorInformationEx(void){}
void GetSystemDirectoryA(void){}
void GetSystemDirectoryW(void){}
void GetSystemInfo(void){}
void GetSystemTime(void){}
void GetSystemTimeAdjustment(void){}
void GetSystemTimeAsFileTime(void){}
void GetSystemWindowsDirectoryA(void){}
void GetSystemWindowsDirectoryW(void){}
void GetTickCount(void){}
void GetTickCount64(void){}
void GetVersion(void){}
void GetVersionExA(void){}
void GetVersionExW(void){}
void GetWindowsDirectoryA(void){}
void GetWindowsDirectoryW(void){}
void GlobalMemoryStatusEx(void){}
void SetLocalTime(void){}
