//---------------------------------------------------------------------------
//
// Microsoft Windows
// Copyright (c) 2006 Microsoft Corporation. All rights reserved.
//
// Defines for the rc file (basebrd.rc).
//---------------------------------------------------------------------------
#define IDRC_BRANDING                                                       1
#define IDS_LEGALCOPYRIGHT                                                 14
#define IDS_COMPANYNAME                                                    15
#define IDS_WINDOWS_LIVE_ID                                                22
#define IDS_WINDOWS_LIVE_ID_PLURAL                                         23
#define IDS_WINDOWS_7                                                      30
#define IDS_WINDOWS_SERVER_7                                               31
#define IDS_WINDOWS_8                                                      32
#define IDS_WINDOWS_SERVER_8                                               33
#define IDS_WINDOWS_XP_ARM                                                 34
#define IDS_WINDOWS_81                                                     35
#define IDS_WINDOWS_SERVER_81                                              36
#define IDS_WINDOWS_XP_ARM_SE                                              37
#define IDS_WHISTLER_BETA                                                  38
#define IDS_WHISTLER_SERVER_BETA                                           39
#define IDS_WHISTLER_BETA2                                                 50
#define IDS_WINDOWS_10                                                     51
#define IDS_WINDOWS_SERVER_2016                                            52
#define IDS_WINDOWS_SERVER_2019                                            53
#define IDS_WHISTLER_SERVER                                                54
#define IDS_WINDOWS_SERVER_2022                                            55
#define IDS_WINDOWS_SERVER_11                                              56
#define IDB_LOGONBANNER1                                                  122
#define IDB_ABOUT1                                                        123
#define IDB_ABOUT_EMBEDDED1                                               124
#define IDS_WINDOWS                                                       200
#define IDS_WINNT                                                         202
#define IDS_WINDOWS_10_2                                                  207
#define IDS_WINNT_EMBEDDED                                                208
#define IDS_WHISTLER_PERSONAL_PLACEHOLDER_1                               272
#define IDS_WHISTLER_PERSONAL_PLACEHOLDER_2                               273
#define IDS_WHISTLER_PERSONAL_PLACEHOLDER_CHINA_1                         284
#define IDS_WHISTLER_PERSONAL_PLACEHOLDER_CHINA_2                         285
#define IDS_WHISTLER_PERSONAL_PLACEHOLDER_EUROPEANUNION_1                 286
#define IDS_WHISTLER_PERSONAL_PLACEHOLDER_EUROPEANUNION_2                 287
#define IDS_WHISTLER_PERSONAL_UNILNG_PLACEHOLDER_1                        288
#define IDS_WHISTLER_PERSONAL_UNILNG_PLACEHOLDER_2                        289
#define IDS_WHISTLER_EDU_PLACEHOLDER_1                                    290
#define IDS_WHISTLER_EDU_PLACEHOLDER_2                                    291
#define IDS_WHISTLER_EDU_EUROPE_PLACEHOLDER_1                             292
#define IDS_WHISTLER_EDU_EUROPE_PLACEHOLDER_2                             293
#define IDS_WHISTLER_EDU_A3_PLACEHOLDER_1                                 294
#define IDS_WHISTLER_EDU_A5_PLACEHOLDER_2                                 295
#define IDS_WHISTLER_ENT_E3_PLACEHOLDER_2                                 296
#define IDS_WHISTLER_ENTERPRISE_PLACEHOLDER_1                             314
#define IDS_WHISTLER_ENTERPRISE_PLACEHOLDER_2                             315
#define IDS_WHISTLER_ENTERPRISE_EVAL_PLACEHOLDER_1                        316
#define IDS_WHISTLER_ENTERPRISE_EVAL_PLACEHOLDER_2                        317
#define IDS_WHISTLER_ENTERPRISE_EUROPE_PLACEHOLDER_1                      318
#define IDS_WHISTLER_ENTERPRISE_EUROPE_PLACEHOLDER_2                      319
#define IDS_WHISTLER_ENTERPRISE_EUROPE_EVAL_PLACEHOLDER_1                 320
#define IDS_WHISTLER_ENTERPRISE_EUROPE_EVAL_PLACEHOLDER_2                 321
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_PLACEHOLDER_1              322
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_PLACEHOLDER_2              323
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_EVAL_PLACEHOLDER_1         324
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_EVAL_PLACEHOLDER_2         325
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_EUROPE_PLACEHOLDER_1       326
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_EUROPE_PLACEHOLDER_2       327
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_EUROPE_EVAL_PLACEHOLDER_1  328
#define IDS_WHISTLER_LONG_TERM_SUPPORT_CHANNEL_EUROPE_EVAL_PLACEHOLDER_2  329
#define IDS_WHISTLER_PPIPRO_SURFACE_HUB_1                                 330
#define IDS_WHISTLER_PPIPRO_SURFACE_HUB_2                                 331
#define IDS_WIN2K_PROFESSIONAL_PLACEHOLDER_1                              332
#define IDS_WIN2K_PROFESSIONAL_PLACEHOLDER_2                              333
#define IDS_WIN2K_PROFESSIONAL_EUROPE_PLACEHOLDER_1                       334
#define IDS_WIN2K_PROFESSIONAL_EUROPE_PLACEHOLDER_2                       335
#define IDS_WINXP_STARTER_SKU_LONG                                        346
#define IDS_WINXP_STARTER_SKU_SHORT                                       347
#define IDS_WINXP_STARTER_SKU_EUROPE_LONG                                 348
#define IDS_WINXP_STARTER_SKU_EUROPE_SHORT                                349
#define IDS_WIN2K_PRO_CHINA_1                                             354
#define IDS_WIN2K_PRO_CHINA_2                                             355
#define IDS_WIN2K_PRO_UNILANG_1                                           356
#define IDS_WIN2K_PRO_UNILANG_2                                           357
#define IDS_WIN2K_PRO_WORKSTATION_PLACEHOLDER_1                           358
#define IDS_WIN2K_PRO_WORKSTATION_PLACEHOLDER_2                           359
#define IDS_WIN2K_PRO_WORKSTATION_EUR_PLACEHOLDER_1                       360
#define IDS_WIN2K_PRO_WORKSTATION_EUR_PLACEHOLDER_2                       361
#define IDS_WIN2K_PROFESSIONAL_STUDENT_PLACEHOLDER_1                      362
#define IDS_WIN2K_PROFESSIONAL_STUDENT_PLACEHOLDER_2                      363
#define IDS_WIN2K_PROFESSIONAL_EUR_STUDENT_PLACEHOLDER_1                  364
#define IDS_WIN2K_PROFESSIONAL_EUR_STUDENT_PLACEHOLDER_2                  365
#define IDS_WINDOWS_LONGHORN_BUSINESS_PLACEHOLDER_1                       366
#define IDS_WINDOWS_LONGHORN_BUSINESS_PLACEHOLDER_2                       367
#define IDS_WINDOWS_LONGHORN_BUSINESS_EUROPE_PLACEHOLDER_1                368
#define IDS_WINDOWS_LONGHORN_BUSINESS_EUROPE_PLACEHOLDER_2                369
#define IDS_WINDOWS_ENTERPRISE_G_PLACEHOLDER_1                            374
#define IDS_WINDOWS_ENTERPRISE_G_PLACEHOLDER_2                            375
#define IDS_WINDOWS_ENTERPRISE_G_EUR_PLACEHOLDER_1                        376
#define IDS_WINDOWS_ENTERPRISE_G_EUR_PLACEHOLDER_2                        377
#define IDS_WINDOWS_ENTERPRISE_MULTIPROCESSOR_PLACEHOLDER_1               382
#define IDS_WINDOWS_ENTERPRISE_MULTIPROCESSOR_PLACEHOLDER_2               383
#define IDS_WINDOWS_INTERNET_OF_THINGS_PLACEHOLDER_1                      388
#define IDS_WINDOWS_INTERNET_OF_THINGS_PLACEHOLDER_2                      389
#define IDS_WINDOWS_INTERNET_OF_THINGS_PROLONGED_UPD_PLACEHOLDER_1        390
#define IDS_WINDOWS_INTERNET_OF_THINGS_PROLONGED_UPD_PLACEHOLDER_2        391
#define IDS_WINDOWS_CLOUD_EDITION_PLACEHOLDER_1                           392
#define IDS_WINDOWS_CLOUD_EDITION_PLACEHOLDER_2                           393
#define IDS_WINDOWS_EUROPEAN_CLOUD_EDITION_PLACEHOLDER_1                  394
#define IDS_WINDOWS_EUROPEAN_CLOUD_EDITION_PLACEHOLDER_2                  395
#define IDS_WINDOWS_IOT_MICROSOFT_SUBSCRIPTION_LTSC_PLACEHOLDER_1         396
#define IDS_WINDOWS_IOT_MICROSOFT_SUBSCRIPTION_LTSC_PLACEHOLDER_2         397
#define IDS_MICROSOFT_WINDOWS_365_PC_PLACEHOLDER_1                        398
#define IDS_MICROSOFT_WINDOWS_365_PC_PLACEHOLDER_2                        399
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_SUBSCRIPTION1                400
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_SUBSCRIPTION2                401
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_LTSC_SUBSCRIPTION1           402
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_LTSC_SUBSCRIPTION2           403
#define IDB_LOGONBANNER2                                                 1122
#define IDB_ABOUT2                                                       1123
#define IDB_ABOUT_EMBEDDED2                                              1124
#define IDB_LOGONBANNER3                                                 2122
#define IDB_ABOUT3                                                       2123
#define IDB_ABOUT_EMBEDDED3                                              2124
#define IDS_IN_PROTECTED_MODE                                            4000
#define IDS_INSIDER_PREVIEW                                              4001
#define IDRCAP_BRANDING                           RES_REQUIRED_RESOURCEID_MAP
#define IDRCMETADATA_BRANDING                                    RES_METADATA
