void I_QueryTagInformation(void){}
void I_ScBroadcastServiceControlMessage(void){}
void I_ScIsSecurityProcess(void){}
void I_ScPnPGetServiceName(void){}
void I_ScQueryServiceConfig(void){}
void I_ScRegisterDeviceNotification(void){}
void I_ScRegisterPreshutdownRestart(void){}
void I_ScRpcBindA(void){}
void I_ScRpcBindW(void){}
void I_ScSendPnPMessage(void){}
void I_ScSendTSMessage(void){}
void I_ScSetServiceBitsA(void){}
void I_ScSetServiceBitsW(void){}
void I_ScUnregisterDeviceNotification(void){}
void I_ScValidatePnPService(void){}
void SubscribeServiceChangeNotifications(void){}
void UnsubscribeServiceChangeNotifications(void){}
void WaitServiceState(void){}
