void CLSIDFromProgID(void){}
void CLSIDFromString(void){}
void CoAddRefServerProcess(void){}
void CoCancelCall(void){}
void CoCopyProxy(void){}
void CoCreateFreeThreadedMarshaler(void){}
void CoCreateGuid(void){}
void CoCreateInstance(void){}
void CoCreateInstanceEx(void){}
void CoDisableCallCancellation(void){}
void CoDisconnectContext(void){}
void CoDisconnectObject(void){}
void CoEnableCallCancellation(void){}
void CoFreeUnusedLibraries(void){}
void CoFreeUnusedLibrariesEx(void){}
void CoGetApartmentType(void){}
void CoGetCallContext(void){}
void CoGetCallerTID(void){}
void CoGetCancelObject(void){}
void CoGetClassObject(void){}
void CoGetContextToken(void){}
void CoGetCurrentLogicalThreadId(void){}
void CoGetCurrentProcess(void){}
void CoGetDefaultContext(void){}
void CoGetInterfaceAndReleaseStream(void){}
void CoGetMalloc(void){}
void CoGetMarshalSizeMax(void){}
void CoGetObjectContext(void){}
void CoGetPSClsid(void){}
void CoGetStandardMarshal(void){}
void CoGetStdMarshalEx(void){}
void CoGetTreatAsClass(void){}
void CoImpersonateClient(void){}
void CoInitializeEx(void){}
void CoInitializeSecurity(void){}
void CoInvalidateRemoteMachineBindings(void){}
void CoIsHandlerConnected(void){}
void CoLockObjectExternal(void){}
void CoMarshalHresult(void){}
void CoMarshalInterThreadInterfaceInStream(void){}
void CoMarshalInterface(void){}
void CoQueryAuthenticationServices(void){}
void CoQueryClientBlanket(void){}
void CoQueryProxyBlanket(void){}
void CoRegisterClassObject(void){}
void CoRegisterInitializeSpy(void){}
void CoRegisterMessageFilter(void){}
void CoRegisterPSClsid(void){}
void CoRegisterSurrogate(void){}
void CoReleaseMarshalData(void){}
void CoReleaseServerProcess(void){}
void CoResumeClassObjects(void){}
void CoRevertToSelf(void){}
void CoRevokeClassObject(void){}
void CoRevokeInitializeSpy(void){}
void CoSetCancelObject(void){}
void CoSetProxyBlanket(void){}
void CoSuspendClassObjects(void){}
void CoSwitchCallContext(void){}
void CoTaskMemAlloc(void){}
void CoTaskMemFree(void){}
void CoTaskMemRealloc(void){}
void CoTestCancel(void){}
void CoUninitialize(void){}
void CoUnmarshalHresult(void){}
void CoUnmarshalInterface(void){}
void CoWaitForMultipleHandles(void){}
void CreateErrorInfo(void){}
void CreateStreamOnHGlobal(void){}
void FreePropVariantArray(void){}
void GetErrorInfo(void){}
void GetHGlobalFromStream(void){}
void IIDFromString(void){}
void ProgIDFromCLSID(void){}
void PropVariantClear(void){}
void PropVariantCopy(void){}
void SetErrorInfo(void){}
void StringFromCLSID(void){}
void StringFromGUID2(void){}
void StringFromIID(void){}
