void GetAcceptLanguagesW(void){}
void HashData(void){}
void IsCharSpaceA(void){}
void IsCharSpaceW(void){}
void IsInternetESCEnabled(void){}
void ParseURLW(void){}
void PathAddBackslashA(void){}
void PathAddBackslashW(void){}
void PathAddExtensionA(void){}
void PathAddExtensionW(void){}
void PathAppendA(void){}
void PathAppendW(void){}
void PathCanonicalizeA(void){}
void PathCanonicalizeW(void){}
void PathCombineA(void){}
void PathCombineW(void){}
void PathCommonPrefixA(void){}
void PathCommonPrefixW(void){}
void PathCreateFromUrlAlloc(void){}
void PathCreateFromUrlW(void){}
void PathFileExistsA(void){}
void PathFileExistsW(void){}
void PathFindExtensionA(void){}
void PathFindExtensionW(void){}
void PathFindFileNameA(void){}
void PathFindFileNameW(void){}
void PathFindNextComponentA(void){}
void PathFindNextComponentW(void){}
void PathGetArgsA(void){}
void PathGetArgsW(void){}
void PathGetCharTypeA(void){}
void PathGetCharTypeW(void){}
void PathGetDriveNumberA(void){}
void PathGetDriveNumberW(void){}
void PathIsFileSpecA(void){}
void PathIsFileSpecW(void){}
void PathIsLFNFileSpecA(void){}
void PathIsLFNFileSpecW(void){}
void PathIsPrefixA(void){}
void PathIsPrefixW(void){}
void PathIsRelativeA(void){}
void PathIsRelativeW(void){}
void PathIsRootA(void){}
void PathIsRootW(void){}
void PathIsSameRootA(void){}
void PathIsSameRootW(void){}
void PathIsUNCA(void){}
void PathIsUNCServerA(void){}
void PathIsUNCServerShareA(void){}
void PathIsUNCServerShareW(void){}
void PathIsUNCServerW(void){}
void PathIsUNCW(void){}
void PathIsURLW(void){}
void PathMatchSpecA(void){}
void PathMatchSpecExA(void){}
void PathMatchSpecExW(void){}
void PathMatchSpecW(void){}
void PathParseIconLocationA(void){}
void PathParseIconLocationW(void){}
void PathQuoteSpacesA(void){}
void PathQuoteSpacesW(void){}
void PathRelativePathToA(void){}
void PathRelativePathToW(void){}
void PathRemoveBackslashA(void){}
void PathRemoveBackslashW(void){}
void PathRemoveBlanksA(void){}
void PathRemoveBlanksW(void){}
void PathRemoveExtensionA(void){}
void PathRemoveExtensionW(void){}
void PathRemoveFileSpecA(void){}
void PathRemoveFileSpecW(void){}
void PathRenameExtensionA(void){}
void PathRenameExtensionW(void){}
void PathSearchAndQualifyA(void){}
void PathSearchAndQualifyW(void){}
void PathSkipRootA(void){}
void PathSkipRootW(void){}
void PathStripPathA(void){}
void PathStripPathW(void){}
void PathStripToRootA(void){}
void PathStripToRootW(void){}
void PathUnExpandEnvStringsA(void){}
void PathUnExpandEnvStringsW(void){}
void PathUnquoteSpacesA(void){}
void PathUnquoteSpacesW(void){}
void QISearch(void){}
void SHLoadIndirectString(void){}
void SHRegCloseUSKey(void){}
void SHRegDeleteUSValueA(void){}
void SHRegDeleteUSValueW(void){}
void SHRegEnumUSKeyA(void){}
void SHRegEnumUSKeyW(void){}
void SHRegGetBoolUSValueA(void){}
void SHRegGetBoolUSValueW(void){}
void SHRegGetUSValueA(void){}
void SHRegGetUSValueW(void){}
void SHRegOpenUSKeyA(void){}
void SHRegOpenUSKeyW(void){}
void SHRegQueryUSValueA(void){}
void SHRegQueryUSValueW(void){}
void SHRegSetUSValueA(void){}
void SHRegSetUSValueW(void){}
void StrCSpnA(void){}
void StrCSpnIA(void){}
void StrCSpnIW(void){}
void StrCSpnW(void){}
void StrCatBuffA(void){}
void StrCatBuffW(void){}
void StrCatChainW(void){}
void StrChrA(void){}
void StrChrIA(void){}
void StrChrIW(void){}
void StrChrNIW(void){}
void StrChrNW(void){}
void StrChrW(void){}
void StrCmpCA(void){}
void StrCmpCW(void){}
void StrCmpICA(void){}
void StrCmpICW(void){}
void StrCmpIW(void){}
void StrCmpLogicalW(void){}
void StrCmpNA(void){}
void StrCmpNCA(void){}
void StrCmpNCW(void){}
void StrCmpNIA(void){}
void StrCmpNICA(void){}
void StrCmpNICW(void){}
void StrCmpNIW(void){}
void StrCmpNW(void){}
void StrCmpW(void){}
void StrCpyNW(void){}
void StrDupA(void){}
void StrDupW(void){}
void StrIsIntlEqualA(void){}
void StrIsIntlEqualW(void){}
void StrPBrkA(void){}
void StrPBrkW(void){}
void StrRChrA(void){}
void StrRChrIA(void){}
void StrRChrIW(void){}
void StrRChrW(void){}
void StrRStrIA(void){}
void StrRStrIW(void){}
void StrSpnA(void){}
void StrSpnW(void){}
void StrStrA(void){}
void StrStrIA(void){}
void StrStrIW(void){}
void StrStrNIW(void){}
void StrStrNW(void){}
void StrStrW(void){}
void StrToInt64ExA(void){}
void StrToInt64ExW(void){}
void StrToIntA(void){}
void StrToIntExA(void){}
void StrToIntExW(void){}
void StrToIntW(void){}
void StrTrimA(void){}
void StrTrimW(void){}
void UrlApplySchemeW(void){}
void UrlCanonicalizeW(void){}
void UrlCombineA(void){}
void UrlCombineW(void){}
void UrlCreateFromPathW(void){}
void UrlEscapeW(void){}
void UrlFixupW(void){}
void UrlGetLocationW(void){}
void UrlGetPartW(void){}
void UrlIsW(void){}
void UrlUnescapeA(void){}
void UrlUnescapeW(void){}
