void CM_Delete_Class_Key(void){}
void CM_Delete_DevNode_Key(void){}
void CM_Delete_Device_Interface_KeyW(void){}
void CM_Disable_DevNode(void){}
void CM_Enable_DevNode(void){}
void CM_Get_Child(void){}
void CM_Get_Class_PropertyW(void){}
void CM_Get_Class_Property_Keys(void){}
void CM_Get_Class_Registry_PropertyW(void){}
void CM_Get_Depth(void){}
void CM_Get_DevNode_PropertyW(void){}
void CM_Get_DevNode_Property_Keys(void){}
void CM_Get_DevNode_Registry_PropertyW(void){}
void CM_Get_DevNode_Status(void){}
void CM_Get_Device_IDW(void){}
void CM_Get_Device_ID_ListW(void){}
void CM_Get_Device_ID_List_SizeW(void){}
void CM_Get_Device_ID_Size(void){}
void CM_Get_Device_Interface_ListW(void){}
void CM_Get_Device_Interface_List_SizeW(void){}
void CM_Get_Device_Interface_PropertyW(void){}
void CM_Get_Device_Interface_Property_KeysW(void){}
void CM_Get_Parent(void){}
void CM_Get_Sibling(void){}
void CM_Locate_DevNodeW(void){}
void CM_Open_Class_KeyW(void){}
void CM_Open_DevNode_Key(void){}
void CM_Open_Device_Interface_KeyW(void){}
void CM_Query_And_Remove_SubTreeW(void){}
void CM_Register_Notification(void){}
void CM_Set_Class_PropertyW(void){}
void CM_Set_Class_Registry_PropertyW(void){}
void CM_Set_DevNode_PropertyW(void){}
void CM_Set_DevNode_Registry_PropertyW(void){}
void CM_Set_Device_Interface_PropertyW(void){}
void CM_Setup_DevNode(void){}
void CM_Uninstall_DevNode(void){}
void CM_Unregister_Notification(void){}
