# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the STRIPINF utility

UI=..\..

USE_MSVCRT=1

#!include rules.mk

!IFDEF NTMAKEENV

!INCLUDE $(NTMAKEENV)\makefile.def

!ENDIF	# NTMAKEENV
