
typedef struct _COPY_PATHS {
	wchar_t *SourcePath;
	wchar_t *DestinationPath;
} _COPY_PATHS;

typedef enum eBOOT_PREP_COPY_TYPES {
	BOOT_PREP_COPY_DIRECTORY_SOURCE = 0,
	BOOT_PREP_COPY_DIRECTORY_DESTINATION = 1,
	BOOT_PREP_COPY_FILE_SOURCE = 2,
	BOOT_PREP_COPY_FILE_DESTINATION = 3,
	BOOT_PREP_COPY_SDDL_SOURCE = 4,
	BOOT_PREP_COPY_SDDL_DESTINATION = 5,
	BOOT_PREP_COPY_ATTRIBUTE_SOURCE = 6,
	BOOT_PREP_COPY_ATTRIBUTE_DESTINATION = 7
} eBOOT_PREP_COPY_TYPES;
