// consoleloghandler.cpp

#include <windows.h>

namespace UnBCL {

class ConsoleLogHandler
{
public:
    // Default constructor
    ConsoleLogHandler();

    // Copy constructor
    ConsoleLogHandler(const ConsoleLogHandler& other);

    // Example virtual method to ensure vtable generation
    virtual void Log(const wchar_t* message);
};

// Default constructor
ConsoleLogHandler::ConsoleLogHandler()
{
    // No-op — vtable is auto-generated by compiler
}

// Copy constructor
ConsoleLogHandler::ConsoleLogHandler(const ConsoleLogHandler& other)
{
    // Copy logic if needed, otherwise no-op
}

// Dummy virtual function to simulate behavior
void ConsoleLogHandler::Log(const wchar_t* message)
{
    if (message)
    {
        OutputDebugStringW(L"[ConsoleLogHandler] ");
        OutputDebugStringW(message);
        OutputDebugStringW(L"\n");
    }
}

} // namespace UnBCL

