//---------------------------------------------------------------------------
//
// Microsoft Windows
// Copyright (c) 2006 Microsoft Corporation. All rights reserved.
//
// Defines for the rc file (basebrd.rc).
//---------------------------------------------------------------------------
#define IDRC_BRANDING                                                       1
#define IDS_LEGALCOPYRIGHT                                                 14
#define IDS_COMPANYNAME                                                    15
#define IDS_WINDOWS_LIVE_ID                                                22
#define IDS_WINDOWS_LIVE_ID_PLURAL                                         23
#define IDS_WINDOWS_7                                                      30
#define IDS_WINDOWS_SERVER_7                                               31
#define IDS_WINDOWS_8                                                      32
#define IDS_WINDOWS_SERVER_8                                               33
#define IDS_WINDOWS_XP_ARM                                                 34
#define IDS_WINDOWS_81                                                     35
#define IDS_WINDOWS_SERVER_81                                              36
#define IDS_WINDOWS_XP_ARM_SE                                              37
#define IDS_WHISTLER_BETA                                                  38
#define IDS_WHISTLER_SERVER_BETA                                           39
#define IDS_WHISTLER_BETA2                                                 50
#define IDS_WINDOWS_10                                                     51
#define IDS_WINDOWS_SERVER_2016                                            52
#define IDS_WINDOWS_SERVER_2019                                            53
#define IDS_WHISTLER_SERVER                                                54
#define IDS_WINDOWS_SERVER_2022                                            55
#define IDS_WINDOWS_SERVER_11                                              56
#define IDB_LOGONBANNER1                                                  122
#define IDB_ABOUT_EMBEDDED1                                               124
#define IDB_ABOUT_EMBEDDED1_2                                             125
#define IDB_ABOUT_EMBEDDED1_3                                             126
#define IDB_ABOUT_WINSRV2012_1                                            127
#define IDB_ABOUT_OUTLINE_1                                               128
#define IDS_WINDOWSSERVER                                                 201
#define IDS_HYPERVSERVER                                                  203
#define IDS_WINDOWS_SRV_2                                                 204
#define IDS_BLADE_SERVER_WHISTLER                                         206
#define IDS_WINNT_EMBEDDED                                                208
#define IDS_WINDOWS_2000_SERVER                                           209
#define IDS_VIRTUAL_PC_SERVER                                             210
#define IDS_WHISTLER_BLADE_SRV                                            213
#define IDS_WHISTLER_SRV                                                  214
#define IDS_AZURE_HCI_STACK                                               215
#define IDS_AZURE_HCI_STACK2                                              216
#define IDS_WHISTLER_EDU_PLACEHOLDER_1                                    290
#define IDS_WHISTLER_EDU_PLACEHOLDER_2                                    291
#define IDS_WIN2K_DATACENTER_SRV                                          352
#define IDS_WIN2K_DATACENTER_SRV2                                         353
#define IDS_WIN2K_PRO_CHINA_1                                             354
#define IDS_WIN2K_PRO_CHINA_2                                             355
#define IDS_WIN2K_PRO_WORKSTATION_PLACEHOLDER_1                           358
#define IDS_WIN2K_PRO_WORKSTATION_PLACEHOLDER_2                           359
#define IDS_WIN2K_PROFESSIONAL_STUDENT_PLACEHOLDER_1                      362
#define IDS_WIN2K_PROFESSIONAL_STUDENT_PLACEHOLDER_2                      363
#define IDS_WIN2K_PROFESSIONAL_EUR_STUDENT_PLACEHOLDER_1                  364
#define IDS_WIN2K_PROFESSIONAL_EUR_STUDENT_PLACEHOLDER_2                  365
#define IDS_WINDOWS_ENTERPRISE_G_PLACEHOLDER_1                            374
#define IDS_WINDOWS_ENTERPRISE_G_PLACEHOLDER_2                            375
#define IDS_WINDOWS_ENTERPRISE_MULTIPROCESSOR_PLACEHOLDER_1               382
#define IDS_WINDOWS_ENTERPRISE_MULTIPROCESSOR_PLACEHOLDER_2               383
#define IDS_WINDOWS_INTERNET_OF_THINGS_PROLONGED_UPD_PLACEHOLDER_1        390
#define IDS_WINDOWS_INTERNET_OF_THINGS_PROLONGED_UPD_PLACEHOLDER_2        391
#define IDS_WINDOWS_CLOUD_EDITION_PLACEHOLDER_1                           392
#define IDS_WINDOWS_CLOUD_EDITION_PLACEHOLDER_2                           393
#define IDS_WINDOWS_EUROPEAN_CLOUD_EDITION_PLACEHOLDER_1                  394
#define IDS_WINDOWS_EUROPEAN_CLOUD_EDITION_PLACEHOLDER_2                  395
#define IDS_WINDOWS_IOT_MICROSOFT_SUBSCRIPTION_LTSC_PLACEHOLDER_1         396
#define IDS_WINDOWS_IOT_MICROSOFT_SUBSCRIPTION_LTSC_PLACEHOLDER_2         397
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_SUBSCRIPTION1                400
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_SUBSCRIPTION2                401
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_LTSC_SUBSCRIPTION1           402
#define IDS_MICROSOFT_WINDOWS_IOT_ENTERPRISE_LTSC_SUBSCRIPTION2           403
#define IDS_MICROSOFT_WHISTLER_DATACENTER_SERVER_AZURE_EDITION            404
#define IDS_MICROSOFT_WHISTLER_DATACENTER_SERVER_AZURE_EDITION2           405
#define IDS_MICROSOFT_WHISTLER_DATACENTER_SERVER_AZURE_EDITION3           406
#define IDS_MICROSOFT_WHISTLER_DATACENTER_SERVER_AZURE_EDITION4           407
#define IDS_SERVER_NANOTEST1                                              500
#define IDS_SERVER_NANOTEST2                                              501
#define IDS_SERVER_NANOTEST3                                              502
#define IDS_SERVER_NANOTEST4                                              503
#define IDS_SERVER_NANOTEST5                                              504
#define IDS_SERVER_NANOTEST6                                              505
#define IDS_SERVER_DATACENTER_WITH_DESKTOP_EXPERIENCE                     506
#define IDS_SERVER_DATACENTER_WITH_DESKTOP_DESC                           507
#define IDS_SERVER_DATACENTER                                             508
#define IDS_SERVER_DATACENTER_DESC                                        509
#define IDS_SERVER_DATACENTER_ONDEMAND                                    510
#define IDS_SERVER_DATACENTER_ONDEMAND_DESC                               511
#define IDS_DATACENTER_EVAL_DESKTOP_EXPERIENCE                            512
#define IDS_DATACENTER_EVAL_DESKTOP_EXPERIENCE_DESC                       513
#define IDS_DATACENTER_EVAL                                               514
#define IDS_DATACENTER_EVAL_DESC                                          515
#define IDS_DATACENTER_EVAL_ONDEMAND                                      516
#define IDS_DATACENTER_EVAL_ONDEMAND_DESC                                 517
#define IDS_HYPERVSERVER_SETUP                                            524
#define IDS_HYPERVSERVER_SETUP_DESC                                       525
#define IDS_STANDARD_SERVER_DESKTOP                                       528
#define IDS_STANDARD_SERVER_DESKTOP_DESC                                  529
#define IDS_STANDARD_SERVER                                               530
#define IDS_STANDARD_SERVER_DESC                                          531
#define IDS_STANDARD_SERVER_ONDEMAND                                      532
#define IDS_STANDARD_SERVER_ONDEMAND_DESC                                 533
#define IDS_STANDARD_SERVER_EVAL_DESKTOP                                  534
#define IDS_STANDARD_SERVER_EVAL_DESKTOP_DESC                             535
#define IDS_STANDARD_SERVER_EVAL                                          536
#define IDS_STANDARD_SERVER_EVAL_DESC                                     537
#define IDS_STANDARD_SERVER_EVAL_ONDEMAND                                 538
#define IDS_STANDARD_SERVER_EVAL_ONDEMAND_DESC                            539
#define IDS_STANDARD_SERVER_BLADE_DESKTOP                                 540
#define IDS_STANDARD_SERVER_BLADE_DESKTOP_DESC                            541
#define IDS_STANDARD_SERVER_BLADE_CMD                                     542
#define IDS_STANDARD_SERVER_BLADE_CMD_DESC                                543
#define IDS_DATACENTER                                                    546
#define IDS_DATACENTER_DESC                                               547
#define IDS_DATACENTER_CMD                                                548
#define IDS_DATACENTER_CMD_DES                                            549
#define IDS_DATACENTER_ONDEMAND                                           550
#define IDS_DATACENTER_ONDEMAND_DES                                       551
#define IDS_STANDARD_DESKTOP                                              562
#define IDS_STANDARD_DESKTOP_DESC                                         563
#define IDS_STANDARD_EVAL_DESKTOP                                         564
#define IDS_STANDARD_EVAL_DESKTOP_DESC                                    565
#define IDS_DTC_DESKTOPEXPERIENCE                                         566
#define IDS_DTC_DESKTOPEXPERIENCE_DESC                                    567
#define IDS_DTC_EVAL_DESKTOPEXPERIENCE                                    568
#define IDS_DTC_EVAL_DESKTOPEXPERIENCE_DESC                               569
#define IDS_AZURE_1                                                       576
#define IDS_AZURE_2                                                       577
#define IDS_AZURE_3                                                       578
#define IDS_AZURE_4                                                       579
#define IDS_AZURE_5                                                       580
#define IDS_AZURE_6                                                       581
#define IDS_AZURE_7                                                       582
#define IDS_AZURE_8                                                       583
#define IDS_AZURE_9                                                       584
#define IDS_AZURE_10                                                      585
#define IDS_AZURE_11                                                      586
#define IDS_AZURE_12                                                      587
#define IDS_AZURE_13                                                      588
#define IDS_AZURE_14                                                      589
#define IDS_AZURE_15                                                      590
#define IDS_AZURE_16                                                      591
#define IDB_LOGONBANNER2                                                 1122
#define IDB_ABOUT_EMBEDDED2                                              1124
#define IDB_ABOUT_EMBEDDED2_2                                            1125
#define IDB_ABOUT_EMBEDDED2_3                                            1126
#define IDB_ABOUT_WINSRV2012_2                                           1127
#define IDB_ABOUT_OUTLINE_2                                              1128
#define IDB_LOGONBANNER3                                                 2122
#define IDB_ABOUT_EMBEDDED3                                              2123
#define IDB_ABOUT_EMBEDDED3_2                                            2124
#define IDB_ABOUT_EMBEDDED3_3                                            2125
#define IDB_ABOUT_WINSRV2012_3                                           2126
#define IDB_ABOUT_OUTLINE_3                                              2128
#define IDS_IN_PROTECTED_MODE                                            4000
#define IDS_INSIDER_PREVIEW                                              4001
#define IDRCAP_BRANDING_OPTIONAL                  RES_OPTIONAL_RESOURCEID_MAP
#define IDRCAP_BRANDING                           RES_REQUIRED_RESOURCEID_MAP
#define IDRCMETADATA_BRANDING                                    RES_METADATA
