void QISearch(void){}
void SHLoadIndirectString(void){}
void StrCSpnA(void){}
void StrCSpnIA(void){}
void StrCSpnIW(void){}
void StrCSpnW(void){}
void StrCatBuffA(void){}
void StrCatBuffW(void){}
void StrCatChainW(void){}
void StrChrA(void){}
void StrChrIA(void){}
void StrChrIW(void){}
void StrChrNIW(void){}
void StrChrNW(void){}
void StrChrW(void){}
void StrCmpCA(void){}
void StrCmpCW(void){}
void StrCmpICA(void){}
void StrCmpICW(void){}
void StrCmpIW(void){}
void StrCmpLogicalW(void){}
void StrCmpNA(void){}
void StrCmpNCA(void){}
void StrCmpNCW(void){}
void StrCmpNIA(void){}
void StrCmpNICA(void){}
void StrCmpNICW(void){}
void StrCmpNIW(void){}
void StrCmpNW(void){}
void StrCmpW(void){}
void StrCpyNW(void){}
void StrCpyNXA(void){}
void StrCpyNXW(void){}
void StrDupA(void){}
void StrDupW(void){}
void StrIsIntlEqualA(void){}
void StrIsIntlEqualW(void){}
void StrPBrkA(void){}
void StrPBrkW(void){}
void StrRChrA(void){}
void StrRChrIA(void){}
void StrRChrIW(void){}
void StrRChrW(void){}
void StrRStrIA(void){}
void StrRStrIW(void){}
void StrSpnA(void){}
void StrSpnW(void){}
void StrStrA(void){}
void StrStrIA(void){}
void StrStrIW(void){}
void StrStrNIW(void){}
void StrStrNW(void){}
void StrStrW(void){}
void StrToInt64ExA(void){}
void StrToInt64ExW(void){}
void StrToIntA(void){}
void StrToIntExA(void){}
void StrToIntExW(void){}
void StrToIntW(void){}
void StrTrimA(void){}
void StrTrimW(void){}
