void AcquireSRWLockExclusive(void){}
void AcquireSRWLockShared(void){}
void CancelWaitableTimer(void){}
void CreateEventA(void){}
void CreateEventExA(void){}
void CreateEventExW(void){}
void CreateEventW(void){}
void CreateMutexA(void){}
void CreateMutexExA(void){}
void CreateMutexExW(void){}
void CreateMutexW(void){}
void CreateSemaphoreExW(void){}
void CreateWaitableTimerExW(void){}
void DeleteCriticalSection(void){}
void EnterCriticalSection(void){}
void InitializeCriticalSection(void){}
void InitializeCriticalSectionAndSpinCount(void){}
void InitializeCriticalSectionEx(void){}
void InitializeSRWLock(void){}
void LeaveCriticalSection(void){}
void OpenEventA(void){}
void OpenEventW(void){}
void OpenMutexW(void){}
void OpenSemaphoreW(void){}
void OpenWaitableTimerW(void){}
void ReleaseMutex(void){}
void ReleaseSRWLockExclusive(void){}
void ReleaseSRWLockShared(void){}
void ReleaseSemaphore(void){}
void ResetEvent(void){}
void SetCriticalSectionSpinCount(void){}
void SetEvent(void){}
void SetWaitableTimer(void){}
void SetWaitableTimerEx(void){}
void SleepEx(void){}
void TryAcquireSRWLockExclusive(void){}
void TryAcquireSRWLockShared(void){}
void TryEnterCriticalSection(void){}
void WaitForMultipleObjectsEx(void){}
void WaitForSingleObject(void){}
void WaitForSingleObjectEx(void){}
